import type { FeatureCopy } from "./feature-copy";

// GENERATED - do not edit by hand. Korean and Japanese copy was localized by a
// writer pass and corrected by a native financial-editor pass.

export const FEATURE_COPY: FeatureCopy = {
  "compare": {
    "en": {
      "title": "{A} vs {B} — Price, Performance & Chart Comparison",
      "description": "Compare {A} and {B} side by side: live prices, day change, 1-month, 6-month and 1-year performance, and 52-week ranges, on one page.",
      "h1": "{A} vs {B}",
      "sub": "Side by side · live prices and performance",
      "hubTitle": "Compare Stocks, Crypto and ETFs Head to Head",
      "hubDescription": "Side-by-side price and performance comparisons — Nvidia vs AMD, Bitcoin vs Ethereum, Samsung vs SK Hynix and more.",
      "hubH1": "Comparisons",
      "hubSub": "{n} head-to-head pages",
      "chartHeading": "1-Year Performance",
      "chartNote": "Both rebased to 0% one year ago",
      "statsHeading": "Side by Side",
      "aboutHeading": "About This Comparison",
      "aboutP": "Both columns use the same live feed and the same closing convention, so the percentages are directly comparable. Performance figures are price return only — they exclude dividends, splits are already adjusted by the data provider, and the two assets may trade in different currencies, which is shown in the table.",
      "popularHeading": "Popular Comparisons",
      "colMetric": "Metric",
      "rowPrice": "Price",
      "rowDayChange": "Day change",
      "row1m": "1-month",
      "row6m": "6-month",
      "row1y": "1-year",
      "rowHigh52": "52-week high",
      "rowLow52": "52-week low",
      "rowCurrency": "Currency",
      "leadBoth": "Over the past year {WINNER} is ahead: {WINNERPCT} against {LOSERPCT} for {LOSER}.",
      "leadTie": "Over the past year the two are near enough level: {LEFTPCT} against {RIGHTPCT}.",
      "leadNoData": "One-year performance is not available for both sides right now.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "{A} vs {B} 시세·수익률 비교 차트",
      "description": "{A}, {B} 두 종목을 나란히 비교합니다. 실시간 시세와 전일 대비 등락률, 1개월·6개월·1년 수익률, 52주 최고·최저가를 한 페이지에 정리했고 1년 수익률 차트로 추이까지 확인할 수 있습니다.",
      "h1": "{A} vs {B}",
      "sub": "나란히 비교 · 실시간 시세와 수익률",
      "hubTitle": "주식·코인·ETF 종목 비교 — 인기 맞대결 한눈에",
      "hubDescription": "엔비디아 vs AMD, 비트코인 vs 이더리움, 삼성전자 vs SK하이닉스처럼 관심 종목을 둘씩 묶어 나란히 비교합니다. 실시간 시세와 전일 대비 등락률, 1년 수익률 차트를 한 페이지에서 확인할 수 있습니다.",
      "hubH1": "종목 비교",
      "hubSub": "1:1 비교 페이지 {n}개",
      "chartHeading": "1년 수익률",
      "chartNote": "1년 전 시점을 0%로 맞춰 두 종목을 함께 표시합니다",
      "statsHeading": "한눈에 비교",
      "aboutHeading": "비교 기준 안내",
      "aboutP": "양쪽 모두 같은 실시간 시세 데이터와 같은 종가 기준을 사용하므로 수익률을 그대로 비교할 수 있습니다. 표에 표시되는 수익률은 배당을 제외한 가격 변동만 반영한 수치이며, 액면분할은 데이터 제공사가 이미 조정해 반영했습니다. 두 종목의 거래 통화가 서로 다를 수 있어 통화는 표에 따로 표시합니다.",
      "popularHeading": "인기 비교",
      "colMetric": "항목",
      "rowPrice": "현재가",
      "rowDayChange": "전일 대비",
      "row1m": "1개월",
      "row6m": "6개월",
      "row1y": "1년",
      "rowHigh52": "52주 최고가",
      "rowLow52": "52주 최저가",
      "rowCurrency": "통화",
      "leadBoth": "최근 1년 수익률은 {WINNER} 쪽이 앞섰습니다. {WINNERPCT}를 기록해 {LOSER}의 {LOSERPCT}를 웃돌았습니다.",
      "leadTie": "최근 1년 수익률은 두 종목이 사실상 비슷한 수준입니다. {LEFTPCT} 대 {RIGHTPCT}입니다.",
      "leadNoData": "현재는 양쪽 모두 1년 수익률 데이터를 불러올 수 없습니다.",
      "footer": "시세 정보는 지연될 수 있으며, 투자 참고용으로만 제공됩니다. 투자 권유가 아닙니다."
    },
    "ja": {
      "title": "{A}と{B}を比較｜株価・騰落率・チャート",
      "description": "{A}と{B}の株価を並べて比較できます。リアルタイム価格、前日比、1カ月・6カ月・1年の騰落率、52週高値・安値を1ページにまとめ、1年前を0%に揃えたチャートで2銘柄のパフォーマンスの差もひと目で分かります。",
      "h1": "{A} vs {B}",
      "sub": "並べて比較 · リアルタイム価格と騰落率",
      "hubTitle": "銘柄比較｜株式・暗号資産・ETFを1対1で比較",
      "hubDescription": "エヌビディアとAMD、ビットコインとイーサリアム、サムスン電子とSKハイニックスなど、注目の2銘柄を並べて比較できます。リアルタイム価格や前日比、1年の騰落率を1ページで確認でき、人気の組み合わせから選べます。",
      "hubH1": "銘柄比較",
      "hubSub": "{n}件の比較ページ",
      "chartHeading": "1年間のパフォーマンス",
      "chartNote": "両銘柄とも1年前を0%として指数化しています",
      "statsHeading": "並べて比較",
      "aboutHeading": "この比較について",
      "aboutP": "左右の列は同じリアルタイムデータと同じ終値基準を用いているため、騰落率をそのまま比較できます。パフォーマンスは値上がり・値下がりだけを反映した価格リターンで、配当は含みません。株式分割はデータ提供元で調整済みです。また、2つの銘柄が異なる通貨で取引されている場合があり、その通貨は表内に表示しています。",
      "popularHeading": "人気の銘柄比較",
      "colMetric": "項目",
      "rowPrice": "価格",
      "rowDayChange": "前日比",
      "row1m": "1カ月",
      "row6m": "6カ月",
      "row1y": "1年",
      "rowHigh52": "52週高値",
      "rowLow52": "52週安値",
      "rowCurrency": "通貨",
      "leadBoth": "過去1年間のパフォーマンスは{WINNER}が優勢で、騰落率は{WINNERPCT}、{LOSER}は{LOSERPCT}です。",
      "leadTie": "過去1年間の騰落率はほぼ互角で、{LEFTPCT}に対して{RIGHTPCT}です。",
      "leadNoData": "現在、両銘柄とも1年間の騰落率を取得できません。",
      "footer": "市場データは遅延する場合があります。情報提供のみを目的としており、投資助言ではありません。"
    }
  },
  "invested": {
    "en": {
      "title": "If I Had Invested — Return Calculator",
      "description": "See what a lump sum would be worth today. Pick Bitcoin, Nvidia, Apple, gold or the S&P 500, an amount and a start date, and get the real return from actual closing prices.",
      "h1": "If I Had Invested",
      "sub": "Real closing prices · pick an asset, an amount and a date",
      "formHeading": "Calculate",
      "assetLabel": "Asset",
      "amountLabel": "Amount",
      "startLabel": "Invested",
      "resultHeading": "Result",
      "valueLabel": "Worth today",
      "profitLabel": "Profit",
      "multipleLabel": "Multiple",
      "cagrLabel": "Annualised",
      "boughtLabel": "Bought at",
      "nowLabel": "Price now",
      "unitsLabel": "Units bought",
      "chartHeading": "Value Over Time",
      "tableHeading": "Other Horizons",
      "colHorizon": "Horizon",
      "colValue": "Worth today",
      "colMultiple": "Multiple",
      "aboutHeading": "How This Is Calculated",
      "aboutP1": "The figure is a lump sum bought at the monthly closing price nearest your start date and held to the most recent monthly close, with no further contributions. Units are fractional, so no rounding is applied.",
      "aboutP2": "Price return only — dividends, interest, fees, spreads and taxes are excluded, and past performance says nothing about future returns. Where an asset trades in a currency other than the US dollar, the result is shown in that currency, so the number does not include any exchange-rate move.",
      "unavailable": "Price history for this asset is not available right now.",
      "presetHeading": "Popular Questions",
      "footer": "Figures are historical, exclude fees and taxes, and are provided for information only, not investment advice."
    },
    "ko": {
      "title": "그때 투자했다면? 비트코인·주식 수익률 계산기",
      "description": "그때 목돈을 넣었다면 지금 얼마가 됐을까요? 비트코인, 엔비디아, 애플, 금, S&P 500 중 종목과 투자 금액, 투자 시점을 고르면 실제 월말 종가 기준으로 평가금액과 수익률, 연평균 수익률(CAGR)까지 계산해 드립니다.",
      "h1": "그때 투자했다면",
      "sub": "실제 월말 종가 기준 · 종목, 금액, 투자 시점 선택",
      "formHeading": "계산하기",
      "assetLabel": "종목",
      "amountLabel": "투자 금액",
      "startLabel": "투자 시점",
      "resultHeading": "계산 결과",
      "valueLabel": "현재 평가금액",
      "profitLabel": "평가손익",
      "multipleLabel": "배수",
      "cagrLabel": "연평균 수익률",
      "boughtLabel": "매수 단가",
      "nowLabel": "현재가",
      "unitsLabel": "매수 수량",
      "chartHeading": "평가금액 추이",
      "tableHeading": "기간별 비교",
      "colHorizon": "투자 기간",
      "colValue": "현재 평가금액",
      "colMultiple": "배수",
      "aboutHeading": "계산 방식 안내",
      "aboutP1": "입력하신 투자 시점과 가장 가까운 월말 종가로 목돈을 한 번에 매수한 뒤, 가장 최근 월말 종가까지 그대로 보유한 것으로 계산합니다. 이후 추가 매수는 반영하지 않으며, 수량은 소수점 단위까지 그대로 적용해 반올림하지 않습니다.",
      "aboutP2": "표시되는 수익률은 가격 변동만 반영한 것으로, 배당과 이자, 수수료, 호가 스프레드, 세금은 모두 제외했습니다. 과거 수익률은 미래 수익률을 보장하지 않습니다. 미국 달러가 아닌 통화로 거래되는 자산은 해당 통화를 기준으로 표시하므로, 환율 변동에 따른 손익은 포함되지 않습니다.",
      "unavailable": "이 종목의 과거 시세 데이터는 현재 제공되지 않습니다.",
      "presetHeading": "많이 찾는 질문",
      "footer": "표시된 수치는 과거 데이터를 기준으로 하며 수수료와 세금은 반영하지 않았습니다. 정보 제공 목적으로만 작성되었으며 투자 권유나 자문이 아닙니다."
    },
    "ja": {
      "title": "もしあの時投資していたら｜リターン計算シミュレーター",
      "description": "ビットコイン・エヌビディア・アップル・金・S&P500など、あの時投資していたら今いくらになっていたかを実際の月末終値で計算します。銘柄と金額、投資時期を選ぶだけで、損益や倍率、年率リターンまでひと目でわかります。",
      "h1": "もしあの時投資していたら",
      "sub": "実際の終値で計算 · 銘柄と金額、投資時期を選ぶだけ",
      "formHeading": "条件を入力",
      "assetLabel": "銘柄",
      "amountLabel": "投資金額",
      "startLabel": "投資時期",
      "resultHeading": "計算結果",
      "valueLabel": "現在の評価額",
      "profitLabel": "損益",
      "multipleLabel": "倍率",
      "cagrLabel": "年率リターン",
      "boughtLabel": "購入価格",
      "nowLabel": "現在値",
      "unitsLabel": "購入数量",
      "chartHeading": "評価額の推移",
      "tableHeading": "期間別の結果",
      "colHorizon": "期間",
      "colValue": "現在の評価額",
      "colMultiple": "倍率",
      "aboutHeading": "計算方法について",
      "aboutP1": "指定した投資時期にもっとも近い月末終値で一括購入し、直近の月末終値まで保有し続けた場合の評価額です。その後の追加投資は行わない前提で計算しています。購入数量は小数点以下まで含めて計算するため、端数の切り上げ・切り捨ては行いません。",
      "aboutP2": "計算の対象は値上がり・値下がりによる価格変動のみで、配当や利息、手数料、スプレッド、税金は含みません。また、過去の実績は将来のリターンを示すものでも、保証するものでもありません。米ドル以外の通貨で取引される銘柄はその通貨建てで表示されるため、為替の変動による影響は含まれていません。",
      "unavailable": "この銘柄の価格データは現在取得できません。",
      "presetHeading": "よく調べられている質問",
      "footer": "掲載している数値は過去の実績に基づくもので、手数料や税金は含みません。情報提供のみを目的としたものであり、投資助言ではありません。"
    }
  },
  "movers": {
    "en": {
      "title": "Daily Movers — Today's Gainers & Losers",
      "description": "The biggest movers today across US, Japanese and Korean stocks and the top cryptocurrencies, with a heatmap of the tape.",
      "h1": "Daily Movers",
      "sub": "Gainers · losers · heatmap",
      "heatmapHeading": "Heatmap",
      "gainersHeading": "Top Gainers",
      "losersHeading": "Top Losers",
      "equitiesHeading": "Equities",
      "cryptoHeading": "Crypto",
      "colName": "Name",
      "colLast": "Last",
      "colPct": "% Chg",
      "aboutHeading": "About This Page",
      "aboutP": "Ranked on the move against the previous close, across the most liquid names on this desk. Markets in different time zones are open at different hours, so a quiet session in one region can leave its names clustered near zero while another region does the moving.",
      "unavailable": "Live data is not available right now, so today's ranking cannot be shown.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "오늘의 급등락 종목 — 상승률·하락률 상위",
      "description": "미국·일본·한국 증시의 주요 종목과 시가총액 상위 가상자산 가운데 전일 대비 등락률이 가장 큰 종목을 정리했습니다. 상승률·하락률 상위 종목과 시장 흐름을 한눈에 보여주는 히트맵을 함께 제공합니다.",
      "h1": "오늘의 급등락 종목",
      "sub": "상승률 · 하락률 · 히트맵",
      "heatmapHeading": "히트맵",
      "gainersHeading": "상승률 상위",
      "losersHeading": "하락률 상위",
      "equitiesHeading": "주식",
      "cryptoHeading": "가상자산",
      "colName": "종목명",
      "colLast": "현재가",
      "colPct": "등락률",
      "aboutHeading": "페이지 안내",
      "aboutP": "이 페이지에서는 거래가 가장 활발한 종목을 대상으로 전일 대비 등락률 순으로 순위를 매깁니다. 지역마다 시차가 있어 증시 개장 시간이 다르기 때문에, 한 지역 증시가 한산한 날에는 해당 종목들의 등락률이 0% 부근에 몰리고 그사이 다른 지역 종목들이 상승률·하락률 상위를 채우기도 합니다.",
      "unavailable": "현재 실시간 시세를 불러올 수 없어 오늘의 급등락 순위를 표시할 수 없습니다.",
      "footer": "시세 정보는 지연될 수 있으며, 투자 자문이 아닌 정보 제공을 목적으로 합니다."
    },
    "ja": {
      "title": "本日の値上がり・値下がりランキング｜米国・日本・韓国株と暗号資産",
      "description": "米国株・日本株・韓国株と主要な暗号資産を対象に、本日の値上がり率・値下がり率の上位銘柄を掲載します。前日終値を基準とした騰落率でランキング化し、ヒートマップで市場全体の値動きも一目で把握できます。銘柄比較にもご活用ください。",
      "h1": "本日の値動きランキング",
      "sub": "値上がり・値下がり・ヒートマップ",
      "heatmapHeading": "ヒートマップ",
      "gainersHeading": "値上がり率上位",
      "losersHeading": "値下がり率上位",
      "equitiesHeading": "株式",
      "cryptoHeading": "暗号資産",
      "colName": "銘柄",
      "colLast": "現在値",
      "colPct": "騰落率",
      "aboutHeading": "このページについて",
      "aboutP": "当サイトが取り扱う流動性の高い銘柄を対象に、前日終値からの騰落率で順位付けしています。地域によって取引時間帯が異なるため、ある市場が閑散としている日は、その地域の銘柄の騰落率がゼロ付近に集中し、上位・下位が別の地域の銘柄で占められることもあります。",
      "unavailable": "現在、リアルタイムデータを取得できないため、本日のランキングを表示できません。",
      "footer": "市場データには遅延が生じる場合があります。情報提供のみを目的としており、投資助言ではありません。"
    }
  },
  "search": {
    "en": {
      "title": "Search — Stocks, Crypto, FX and Tools",
      "description": "Search every quote page, currency pair, comparison and tool on PNL404. Results filter as you type.",
      "h1": "Search",
      "sub": "Quotes, currencies, comparisons and tools",
      "placeholder": "Search a ticker, company, currency or tool",
      "noResults": "Nothing matched that. Try a ticker, a company name or a currency code.",
      "emptyPrompt": "Start typing to search across every page on the desk.",
      "resultsCount": "{n} results",
      "browseHeading": "Browse",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "통합 검색 — 주식·코인·환율 시세와 투자 도구",
      "description": "PNL404에 있는 모든 주식·코인 시세 페이지와 환율, 종목 비교, 투자 도구를 한 곳에서 검색할 수 있습니다. 티커나 회사명, 통화 코드를 입력하면 검색 결과가 실시간으로 좁혀집니다.",
      "h1": "검색",
      "sub": "시세, 환율, 종목 비교, 투자 도구",
      "placeholder": "티커, 회사명, 통화, 도구 검색",
      "noResults": "검색 결과가 없습니다. 티커나 회사명, 통화 코드로 다시 검색해 보세요.",
      "emptyPrompt": "검색어를 입력하시면 PNL404의 모든 페이지에서 결과를 바로 찾아 드립니다.",
      "resultsCount": "검색 결과 {n}건",
      "browseHeading": "둘러보기",
      "footer": "시세 정보는 지연될 수 있으며, 투자 자문이 아닌 단순 정보 제공을 목적으로 합니다."
    },
    "ja": {
      "title": "サイト内検索｜株価・仮想通貨・為替・投資ツール",
      "description": "PNL404に掲載しているすべての株価ページ、通貨ペア、銘柄比較、投資ツールをまとめて検索できます。ティッカーや企業名、通貨コードを入力すると、その場で候補が絞り込まれ、目的のページにすぐたどり着けます。",
      "h1": "サイト内検索",
      "sub": "株価・為替・銘柄比較・投資ツール",
      "placeholder": "ティッカー・企業名・通貨・ツール名で検索",
      "noResults": "該当する項目が見つかりませんでした。ティッカーや企業名、通貨コードでお試しください。",
      "emptyPrompt": "キーワードを入力すると、サイト内のすべてのページから検索できます。",
      "resultsCount": "検索結果{n}件",
      "browseHeading": "一覧から探す",
      "footer": "市場データは遅延する場合があります。情報提供を目的としたものであり、投資助言ではありません。"
    }
  },
  "widget": {
    "en": {
      "title": "Free Embeddable Market Ticker Widget",
      "description": "Put a live stock, crypto and FX ticker on your own site. Pick your symbols, copy the iframe, done — no key and no signup.",
      "h1": "Ticker Widget",
      "sub": "Pick symbols · copy the iframe · drop it on any page",
      "previewHeading": "Preview",
      "symbolsHeading": "Symbols",
      "symbolsNote": "Up to 8",
      "snippetHeading": "Embed Code",
      "copyButton": "Copy embed code",
      "copiedButton": "Copied",
      "openEmbed": "Open the widget",
      "resetButton": "Reset",
      "aboutHeading": "How It Works",
      "aboutP": "The iframe loads a lightweight strip that refreshes on its own, with no script to install, no API key and no signup. It inherits nothing from your page's styles, so it looks the same everywhere. Attribution back to this site is appreciated but not required.",
      "emptyNote": "Pick at least one symbol.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "내 사이트에 붙이는 무료 실시간 시세 티커 위젯 (주식·코인·환율)",
      "description": "주식·코인·환율 실시간 시세 티커를 내 사이트에 바로 붙일 수 있습니다. 원하는 종목을 최대 8개까지 고른 뒤 iframe 코드만 복사해 넣으면 끝입니다. API 키도 회원가입도 필요 없고 시세는 자동으로 갱신됩니다.",
      "h1": "시세 티커 위젯",
      "sub": "종목 선택 · iframe 복사 · 어느 페이지에나 붙여넣기",
      "previewHeading": "미리보기",
      "symbolsHeading": "종목",
      "symbolsNote": "최대 8개",
      "snippetHeading": "임베드 코드",
      "copyButton": "임베드 코드 복사",
      "copiedButton": "복사 완료",
      "openEmbed": "위젯 열기",
      "resetButton": "초기화",
      "aboutHeading": "작동 방식",
      "aboutP": "iframe을 넣으면 가벼운 시세 표시줄이 로드되어 별도 조작 없이 스스로 갱신됩니다. 설치할 스크립트도, API 키도, 회원가입도 필요 없습니다. 내 페이지의 스타일을 전혀 상속받지 않기 때문에 어느 사이트에 붙여도 똑같이 보입니다. 이 사이트로 연결되는 출처 링크를 남겨 주시면 감사하지만, 필수는 아닙니다.",
      "emptyNote": "종목을 하나 이상 선택해 주세요.",
      "footer": "시세 정보는 지연될 수 있으며, 투자 자문이 아닌 정보 제공을 목적으로 합니다."
    },
    "ja": {
      "title": "株価ティッカーウィジェット｜仮想通貨・為替対応｜無料で埋め込み",
      "description": "株価・仮想通貨・為替のティッカーを自分のサイトに無料で設置できるウィジェットです。銘柄を選んでiframeタグをコピーし、ページに貼り付けるだけです。APIキーも会員登録も不要で、値動きは自動で更新されます。最大8銘柄まで選べます。",
      "h1": "ティッカーウィジェット",
      "sub": "銘柄を選ぶ · iframeをコピー · 好きなページに貼る",
      "previewHeading": "プレビュー",
      "symbolsHeading": "銘柄",
      "symbolsNote": "最大8銘柄",
      "snippetHeading": "埋め込みコード",
      "copyButton": "コードをコピー",
      "copiedButton": "コピー完了",
      "openEmbed": "ウィジェットを開く",
      "resetButton": "リセット",
      "aboutHeading": "仕組み",
      "aboutP": "iframeが読み込むのは軽量なティッカーだけで、価格は自動で更新されます。スクリプトの設置もAPIキーも会員登録も必要ありません。設置したページのCSSの影響を受けないため、どのサイトでも同じ見た目で表示されます。当サイトへのリンクを添えていただけると励みになりますが、必須ではありません。",
      "emptyNote": "銘柄を1つ以上選んでください。",
      "footer": "市場データは遅延する場合があります。本情報は情報提供のみを目的としたものであり、投資助言ではありません。"
    }
  }
};
