import type { FeatureCopy } from "./feature-copy";

// GENERATED - do not edit by hand. Korean and Japanese copy was localized by a
// writer pass and corrected by a native financial-editor pass.

export const FEATURE_COPY: FeatureCopy = {
  "compare": {
    "en": {
      "title": "{A} vs {B} — Price, Performance & Chart Comparison",
      "description": "Compare {A} and {B} side by side: live prices, day change, 1-month, 6-month and 1-year performance, and 52-week ranges, on one page.",
      "h1": "{A} vs {B}",
      "sub": "Side by side · live prices and performance",
      "hubTitle": "Compare Stocks, Crypto and ETFs Head to Head",
      "hubDescription": "Side-by-side price and performance comparisons — Nvidia vs AMD, Bitcoin vs Ethereum, Samsung vs SK Hynix and more.",
      "hubH1": "Comparisons",
      "hubSub": "{n} head-to-head pages",
      "chartHeading": "1-Year Performance",
      "chartNote": "Both rebased to 0% one year ago",
      "statsHeading": "Side by Side",
      "aboutHeading": "About This Comparison",
      "aboutP": "Both columns use the same live feed and the same closing convention, so the percentages are directly comparable. Performance figures are price return only — they exclude dividends, splits are already adjusted by the data provider, and the two assets may trade in different currencies, which is shown in the table.",
      "popularHeading": "Popular Comparisons",
      "colMetric": "Metric",
      "rowPrice": "Price",
      "rowDayChange": "Day change",
      "row1m": "1-month",
      "row6m": "6-month",
      "row1y": "1-year",
      "rowHigh52": "52-week high",
      "rowLow52": "52-week low",
      "rowCurrency": "Currency",
      "leadBoth": "Over the past year {WINNER} is ahead: {WINNERPCT} against {LOSERPCT} for {LOSER}.",
      "leadTie": "Over the past year the two are near enough level: {LEFTPCT} against {RIGHTPCT}.",
      "leadNoData": "One-year performance is not available for both sides right now.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "{A} vs {B} 시세·수익률 비교 차트",
      "description": "{A}, {B} 두 종목을 나란히 비교합니다. 실시간 시세와 전일 대비 등락률, 1개월·6개월·1년 수익률, 52주 최고·최저가를 한 페이지에 정리했고 1년 수익률 차트로 추이까지 확인할 수 있습니다.",
      "h1": "{A} vs {B}",
      "sub": "나란히 비교 · 실시간 시세와 수익률",
      "hubTitle": "주식·코인·ETF 종목 비교 — 인기 맞대결 한눈에",
      "hubDescription": "엔비디아 vs AMD, 비트코인 vs 이더리움, 삼성전자 vs SK하이닉스처럼 관심 종목을 둘씩 묶어 나란히 비교합니다. 실시간 시세와 전일 대비 등락률, 1년 수익률 차트를 한 페이지에서 확인할 수 있습니다.",
      "hubH1": "종목 비교",
      "hubSub": "1:1 비교 페이지 {n}개",
      "chartHeading": "1년 수익률",
      "chartNote": "1년 전 시점을 0%로 맞춰 두 종목을 함께 표시합니다",
      "statsHeading": "한눈에 비교",
      "aboutHeading": "비교 기준 안내",
      "aboutP": "양쪽 모두 같은 실시간 시세 데이터와 같은 종가 기준을 사용하므로 수익률을 그대로 비교할 수 있습니다. 표에 표시되는 수익률은 배당을 제외한 가격 변동만 반영한 수치이며, 액면분할은 데이터 제공사가 이미 조정해 반영했습니다. 두 종목의 거래 통화가 서로 다를 수 있어 통화는 표에 따로 표시합니다.",
      "popularHeading": "인기 비교",
      "colMetric": "항목",
      "rowPrice": "현재가",
      "rowDayChange": "전일 대비",
      "row1m": "1개월",
      "row6m": "6개월",
      "row1y": "1년",
      "rowHigh52": "52주 최고가",
      "rowLow52": "52주 최저가",
      "rowCurrency": "통화",
      "leadBoth": "최근 1년 수익률은 {WINNER} 쪽이 앞섰습니다. {WINNERPCT}를 기록해 {LOSER}의 {LOSERPCT}를 웃돌았습니다.",
      "leadTie": "최근 1년 수익률은 두 종목이 사실상 비슷한 수준입니다. {LEFTPCT} 대 {RIGHTPCT}입니다.",
      "leadNoData": "현재는 양쪽 모두 1년 수익률 데이터를 불러올 수 없습니다.",
      "footer": "시세 정보는 지연될 수 있으며, 투자 참고용으로만 제공됩니다. 투자 권유가 아닙니다."
    },
    "ja": {
      "title": "{A}と{B}を比較｜株価・騰落率・チャート",
      "description": "{A}と{B}の株価を並べて比較できます。リアルタイム価格、前日比、1カ月・6カ月・1年の騰落率、52週高値・安値を1ページにまとめ、1年前を0%に揃えたチャートで2銘柄のパフォーマンスの差もひと目で分かります。",
      "h1": "{A} vs {B}",
      "sub": "並べて比較 · リアルタイム価格と騰落率",
      "hubTitle": "銘柄比較｜株式・暗号資産・ETFを1対1で比較",
      "hubDescription": "エヌビディアとAMD、ビットコインとイーサリアム、サムスン電子とSKハイニックスなど、注目の2銘柄を並べて比較できます。リアルタイム価格や前日比、1年の騰落率を1ページで確認でき、人気の組み合わせから選べます。",
      "hubH1": "銘柄比較",
      "hubSub": "{n}件の比較ページ",
      "chartHeading": "1年間のパフォーマンス",
      "chartNote": "両銘柄とも1年前を0%として指数化しています",
      "statsHeading": "並べて比較",
      "aboutHeading": "この比較について",
      "aboutP": "左右の列は同じリアルタイムデータと同じ終値基準を用いているため、騰落率をそのまま比較できます。パフォーマンスは値上がり・値下がりだけを反映した価格リターンで、配当は含みません。株式分割はデータ提供元で調整済みです。また、2つの銘柄が異なる通貨で取引されている場合があり、その通貨は表内に表示しています。",
      "popularHeading": "人気の銘柄比較",
      "colMetric": "項目",
      "rowPrice": "価格",
      "rowDayChange": "前日比",
      "row1m": "1カ月",
      "row6m": "6カ月",
      "row1y": "1年",
      "rowHigh52": "52週高値",
      "rowLow52": "52週安値",
      "rowCurrency": "通貨",
      "leadBoth": "過去1年間のパフォーマンスは{WINNER}が優勢で、騰落率は{WINNERPCT}、{LOSER}は{LOSERPCT}です。",
      "leadTie": "過去1年間の騰落率はほぼ互角で、{LEFTPCT}に対して{RIGHTPCT}です。",
      "leadNoData": "現在、両銘柄とも1年間の騰落率を取得できません。",
      "footer": "市場データは遅延する場合があります。情報提供のみを目的としており、投資助言ではありません。"
    }
  },
  "invested": {
    "en": {
      "title": "If I Had Invested — Return Calculator",
      "description": "See what a lump sum would be worth today. Pick Bitcoin, Nvidia, Apple, gold or the S&P 500, an amount and a start date, and get the real return from actual closing prices.",
      "h1": "If I Had Invested",
      "sub": "Real closing prices · pick an asset, an amount and a date",
      "formHeading": "Calculate",
      "assetLabel": "Asset",
      "amountLabel": "Amount",
      "startLabel": "Invested",
      "resultHeading": "Result",
      "valueLabel": "Worth today",
      "profitLabel": "Profit",
      "multipleLabel": "Multiple",
      "cagrLabel": "Annualised",
      "boughtLabel": "Bought at",
      "nowLabel": "Price now",
      "unitsLabel": "Units bought",
      "chartHeading": "Value Over Time",
      "tableHeading": "Other Horizons",
      "colHorizon": "Horizon",
      "colValue": "Worth today",
      "colMultiple": "Multiple",
      "aboutHeading": "How This Is Calculated",
      "aboutP1": "The figure is a lump sum bought at the monthly closing price nearest your start date and held to the most recent monthly close, with no further contributions. Units are fractional, so no rounding is applied.",
      "aboutP2": "Price return only — dividends, interest, fees, spreads and taxes are excluded, and past performance says nothing about future returns. Where an asset trades in a currency other than the US dollar, the result is shown in that currency, so the number does not include any exchange-rate move.",
      "unavailable": "Price history for this asset is not available right now.",
      "presetHeading": "Popular Questions",
      "footer": "Figures are historical, exclude fees and taxes, and are provided for information only, not investment advice."
    },
    "ko": {
      "title": "그때 투자했다면? 비트코인·주식 수익률 계산기",
      "description": "그때 목돈을 넣었다면 지금 얼마가 됐을까요? 비트코인, 엔비디아, 애플, 금, S&P 500 중 종목과 투자 금액, 투자 시점을 고르면 실제 월말 종가 기준으로 평가금액과 수익률, 연평균 수익률(CAGR)까지 계산해 드립니다.",
      "h1": "그때 투자했다면",
      "sub": "실제 월말 종가 기준 · 종목, 금액, 투자 시점 선택",
      "formHeading": "계산하기",
      "assetLabel": "종목",
      "amountLabel": "투자 금액",
      "startLabel": "투자 시점",
      "resultHeading": "계산 결과",
      "valueLabel": "현재 평가금액",
      "profitLabel": "평가손익",
      "multipleLabel": "배수",
      "cagrLabel": "연평균 수익률",
      "boughtLabel": "매수 단가",
      "nowLabel": "현재가",
      "unitsLabel": "매수 수량",
      "chartHeading": "평가금액 추이",
      "tableHeading": "기간별 비교",
      "colHorizon": "투자 기간",
      "colValue": "현재 평가금액",
      "colMultiple": "배수",
      "aboutHeading": "계산 방식 안내",
      "aboutP1": "입력하신 투자 시점과 가장 가까운 월말 종가로 목돈을 한 번에 매수한 뒤, 가장 최근 월말 종가까지 그대로 보유한 것으로 계산합니다. 이후 추가 매수는 반영하지 않으며, 수량은 소수점 단위까지 그대로 적용해 반올림하지 않습니다.",
      "aboutP2": "표시되는 수익률은 가격 변동만 반영한 것으로, 배당과 이자, 수수료, 호가 스프레드, 세금은 모두 제외했습니다. 과거 수익률은 미래 수익률을 보장하지 않습니다. 미국 달러가 아닌 통화로 거래되는 자산은 해당 통화를 기준으로 표시하므로, 환율 변동에 따른 손익은 포함되지 않습니다.",
      "unavailable": "이 종목의 과거 시세 데이터는 현재 제공되지 않습니다.",
      "presetHeading": "많이 찾는 질문",
      "footer": "표시된 수치는 과거 데이터를 기준으로 하며 수수료와 세금은 반영하지 않았습니다. 정보 제공 목적으로만 작성되었으며 투자 권유나 자문이 아닙니다."
    },
    "ja": {
      "title": "もしあの時投資していたら｜リターン計算シミュレーター",
      "description": "ビットコイン・エヌビディア・アップル・金・S&P500など、あの時投資していたら今いくらになっていたかを実際の月末終値で計算します。銘柄と金額、投資時期を選ぶだけで、損益や倍率、年率リターンまでひと目でわかります。",
      "h1": "もしあの時投資していたら",
      "sub": "実際の終値で計算 · 銘柄と金額、投資時期を選ぶだけ",
      "formHeading": "条件を入力",
      "assetLabel": "銘柄",
      "amountLabel": "投資金額",
      "startLabel": "投資時期",
      "resultHeading": "計算結果",
      "valueLabel": "現在の評価額",
      "profitLabel": "損益",
      "multipleLabel": "倍率",
      "cagrLabel": "年率リターン",
      "boughtLabel": "購入価格",
      "nowLabel": "現在値",
      "unitsLabel": "購入数量",
      "chartHeading": "評価額の推移",
      "tableHeading": "期間別の結果",
      "colHorizon": "期間",
      "colValue": "現在の評価額",
      "colMultiple": "倍率",
      "aboutHeading": "計算方法について",
      "aboutP1": "指定した投資時期にもっとも近い月末終値で一括購入し、直近の月末終値まで保有し続けた場合の評価額です。その後の追加投資は行わない前提で計算しています。購入数量は小数点以下まで含めて計算するため、端数の切り上げ・切り捨ては行いません。",
      "aboutP2": "計算の対象は値上がり・値下がりによる価格変動のみで、配当や利息、手数料、スプレッド、税金は含みません。また、過去の実績は将来のリターンを示すものでも、保証するものでもありません。米ドル以外の通貨で取引される銘柄はその通貨建てで表示されるため、為替の変動による影響は含まれていません。",
      "unavailable": "この銘柄の価格データは現在取得できません。",
      "presetHeading": "よく調べられている質問",
      "footer": "掲載している数値は過去の実績に基づくもので、手数料や税金は含みません。情報提供のみを目的としたものであり、投資助言ではありません。"
    }
  },
  "dca": {
    "en": {
      "title": "{NAME} DCA Calculator — Monthly Investing Backtest",
      "description": "See what regularly investing a fixed amount in {NAME} every month would be worth today, using real monthly closing prices — total contributed, current value, average cost and annualised return.",
      "h1": "{NAME} DCA Calculator",
      "sub": "Real monthly closes · pick a monthly amount and a start date",
      "formHeading": "Calculate",
      "amountLabel": "Monthly amount",
      "startLabel": "Since",
      "resultHeading": "Result",
      "monthsNote": "{N} monthly contributions",
      "contributedLabel": "Total contributed",
      "valueLabel": "Worth today",
      "profitLabel": "Profit",
      "totalPctLabel": "Total return",
      "avgCostLabel": "Average cost",
      "annualizedLabel": "Annualised (approx.)",
      "vsLumpHeading": "DCA vs. Lump Sum",
      "vsLumpNote": "The same total put in as a single lump sum on the first contribution date would be worth {LUMP} today, against {DCA} for spreading it out monthly.",
      "chartHeading": "Value Over Time",
      "tableHeading": "Other Horizons",
      "colHorizon": "Since",
      "colValue": "Worth today",
      "colReturn": "Total return",
      "aboutHeading": "How This Is Calculated",
      "aboutP1": "The same fixed amount is bought at every monthly closing price from your start date to the most recent close — no market timing, no skipped months. Units are fractional, so no rounding is applied, and the annualised figure treats the contributions as one lump sum at their dollar-weighted average age, which is an approximation rather than a true internal rate of return.",
      "aboutP2": "Price return only — dividends, interest, fees, spreads and taxes are excluded, and past performance says nothing about future returns. Where an asset trades in a currency other than the US dollar, the result is shown in that currency, so the number does not include any exchange-rate move.",
      "unavailable": "Price history for this asset is not available right now.",
      "presetHeading": "Popular Starting Points",
      "footer": "Figures are historical, exclude fees and taxes, and are provided for information only, not investment advice."
    },
    "ko": {
      "title": "{NAME} 적립식 투자 계산기 — 매달 얼마씩 넣었다면",
      "description": "{NAME}에 매달 일정 금액을 적립식으로 투자했다면 지금 얼마가 됐을지 계산합니다. 실제 월말 종가를 기준으로 총 납입금, 현재 평가금액, 평균 매수 단가, 연평균 수익률까지 확인할 수 있습니다.",
      "h1": "{NAME} 적립식 투자 계산기",
      "sub": "실제 월말 종가 기준 · 매달 납입 금액과 시작 시점 선택",
      "formHeading": "계산하기",
      "amountLabel": "매달 납입 금액",
      "startLabel": "적립 시작",
      "resultHeading": "계산 결과",
      "monthsNote": "총 {N}회 납입",
      "contributedLabel": "총 납입금",
      "valueLabel": "현재 평가금액",
      "profitLabel": "평가손익",
      "totalPctLabel": "누적 수익률",
      "avgCostLabel": "평균 매수 단가",
      "annualizedLabel": "연평균 수익률(근사치)",
      "vsLumpHeading": "적립식 vs. 거치식",
      "vsLumpNote": "같은 총액을 적립 시작 시점에 한 번에 거치식으로 투자했다면 현재 {LUMP}, 매달 나눠 적립했다면 {DCA}입니다.",
      "chartHeading": "평가금액 추이",
      "tableHeading": "기간별 비교",
      "colHorizon": "적립 기간",
      "colValue": "현재 평가금액",
      "colReturn": "누적 수익률",
      "aboutHeading": "계산 방식 안내",
      "aboutP1": "적립 시작 시점부터 가장 최근 월말 종가까지, 매달 같은 금액을 그 달의 종가로 매수했다고 가정해 계산합니다. 특정 달을 건너뛰거나 매수 시점을 조정하지 않으며, 수량은 소수점 단위까지 그대로 적용해 반올림하지 않습니다. 연평균 수익률은 각 납입금을 금액 가중 평균 보유 기간 동안 한 번에 투자한 것으로 가정한 근사치이며, 실제 내부수익률(IRR)과는 차이가 있을 수 있습니다.",
      "aboutP2": "표시되는 수익률은 가격 변동만 반영한 것으로, 배당과 이자, 수수료, 호가 스프레드, 세금은 모두 제외했습니다. 과거 수익률은 미래 수익률을 보장하지 않습니다. 미국 달러가 아닌 통화로 거래되는 자산은 해당 통화를 기준으로 표시하므로, 환율 변동에 따른 손익은 포함되지 않습니다.",
      "unavailable": "이 종목의 과거 시세 데이터는 현재 제공되지 않습니다.",
      "presetHeading": "많이 찾는 종목",
      "footer": "표시된 수치는 과거 데이터를 기준으로 하며 수수료와 세금은 반영하지 않았습니다. 정보 제공 목적으로만 작성되었으며 투자 권유나 자문이 아닙니다."
    },
    "ja": {
      "title": "{NAME} 積立シミュレーション｜毎月いくら積み立てたら",
      "description": "{NAME}に毎月一定額を積み立てていたら今いくらになっていたかを計算します。実際の月末終値をもとに、積立総額・現在の評価額・平均取得単価・年率リターンまでまとめて確認できます。",
      "h1": "{NAME} 積立シミュレーション",
      "sub": "実際の月末終値で計算 · 毎月の積立額と開始時期を選ぶだけ",
      "formHeading": "条件を入力",
      "amountLabel": "毎月の積立額",
      "startLabel": "積立開始",
      "resultHeading": "計算結果",
      "monthsNote": "積立回数 {N}回",
      "contributedLabel": "積立総額",
      "valueLabel": "現在の評価額",
      "profitLabel": "損益",
      "totalPctLabel": "累計リターン",
      "avgCostLabel": "平均取得単価",
      "annualizedLabel": "年率リターン(概算)",
      "vsLumpHeading": "積立投資 vs. 一括投資",
      "vsLumpNote": "同じ総額を積立開始時点で一括投資していた場合の評価額は{LUMP}、毎月積み立てた場合は{DCA}です。",
      "chartHeading": "評価額の推移",
      "tableHeading": "期間別の結果",
      "colHorizon": "積立期間",
      "colValue": "現在の評価額",
      "colReturn": "累計リターン",
      "aboutHeading": "計算方法について",
      "aboutP1": "積立開始時期から直近の月末終値まで、毎月同じ金額をその月の終値で購入し続けたと仮定して計算しています。特定の月を飛ばしたり購入時期を調整したりすることはありません。購入数量は小数点以下まで含めて計算するため、端数の切り上げ・切り捨ては行いません。年率リターンは、積立額を金額加重平均の保有期間で一括投資したものとみなした概算値で、実際の内部収益率(IRR)とは異なる場合があります。",
      "aboutP2": "計算の対象は値上がり・値下がりによる価格変動のみで、配当や利息、手数料、スプレッド、税金は含みません。また、過去の実績は将来のリターンを示すものでも、保証するものでもありません。米ドル以外の通貨で取引される銘柄はその通貨建てで表示されるため、為替の変動による影響は含まれていません。",
      "unavailable": "この銘柄の価格データは現在取得できません。",
      "presetHeading": "よく見られている銘柄",
      "footer": "掲載している数値は過去の実績に基づくもので、手数料や税金は含みません。情報提供のみを目的としたものであり、投資助言ではありません。"
    }
  },
  "gold": {
    "en": {
      "title": "Gold Price Calculator — Price per Gram & per Don (돈)",
      "description": "Live international gold price converted into the units Koreans actually price gold in — 원/g and 원/돈 (1 don = 3.75g) — plus 24K/18K/14K purity, computed from the spot gold price and the dollar/won rate.",
      "h1": "Gold Price Calculator",
      "sub": "International spot price → 원/g and 원/돈, live",
      "formHeading": "Calculate",
      "gramLabel": "Weight (grams)",
      "donLabel": "Weight (don, 1 don = 3.75g)",
      "karatLabel": "Purity",
      "resultHeading": "Result",
      "forWeight": "Price for {N}",
      "perGramLabel": "Per gram",
      "perDonLabel": "Per don (3.75g)",
      "basisHeading": "About This Price",
      "basisNote": "This is the international spot price (COMEX gold futures) converted through the live dollar/won rate — not a retail counter price. Jewelers and gold shops add VAT and a dealer margin on top, so the price you'd actually pay to buy gold runs higher than this figure.",
      "presetHeading": "By the Don",
      "presetLink": "{N} don",
      "donPageTitle": "Gold Price for {N} Don (돈) — Today's Price in Won",
      "donPageDescription": "What {N} don of gold is worth right now, converted from the live international spot price into Korean won, at 24K, 18K and 14K purity.",
      "aboutHeading": "How This Is Calculated",
      "aboutP1": "The gram price comes from the COMEX gold futures price (GC=F, US dollars per troy ounce) divided by 31.1034768 grams per ounce, then converted to won at the live dollar/won rate. The don price is the gram price × 3.75. Purity below 24K scales the price down by karat ÷ 24 (18K = 18/24, 14K = 14/24).",
      "aboutP2": "This is a spot-price conversion, not a store quote. Actual buy and sell prices at a Korean gold shop include value-added tax and a dealer margin on top of the international price, and can also differ from shop to shop.",
      "unavailable": "Live gold and exchange-rate prices are temporarily unavailable, so this calculator cannot show a result right now.",
      "footer": "Prices are for information only, not investment or purchase advice."
    },
    "ko": {
      "title": "금 시세 계산기 — 원/g · 원/돈 환산 (오늘 금값)",
      "description": "국제 금 시세를 원/g, 원/돈(1돈=3.75g) 단위로 환산해 보여드립니다. 24K·18K·14K 순도별 가격까지, 실시간 금 선물 시세와 달러 환율을 기준으로 계산합니다.",
      "h1": "금 시세 계산기",
      "sub": "국제 금 시세 → 원/g · 원/돈, 실시간 환산",
      "formHeading": "계산하기",
      "gramLabel": "무게(그램)",
      "donLabel": "무게(돈, 1돈 = 3.75g)",
      "karatLabel": "순도",
      "resultHeading": "계산 결과",
      "forWeight": "{N} 가격",
      "perGramLabel": "1g당",
      "perDonLabel": "1돈(3.75g)당",
      "basisHeading": "이 가격에 대해",
      "basisNote": "이 금액은 국제 금 시세(COMEX 금 선물)를 실시간 달러·원 환율로 환산한 국제 시세 환산 기준이며, 금은방·귀금속점의 판매가가 아닙니다. 실제 매장에서 살 때는 여기에 부가세와 판매 마진이 더해지므로, 실제 구매가는 이 금액보다 높습니다.",
      "presetHeading": "돈 단위로 보기",
      "presetLink": "{N}돈",
      "donPageTitle": "금 {N}돈 시세 — 오늘 원화로 얼마?",
      "donPageDescription": "금 {N}돈이 지금 원화로 얼마인지, 국제 금 시세를 실시간으로 환산해 24K·18K·14K 순도별로 보여드립니다.",
      "aboutHeading": "계산 방식 안내",
      "aboutP1": "1g 가격은 COMEX 금 선물 시세(GC=F, 트로이온스당 달러)를 온스당 31.1034768g으로 나눈 뒤, 실시간 달러·원 환율로 환산한 값입니다. 1돈 가격은 1g 가격에 3.75를 곱한 값입니다. 24K 미만 순도는 캐럿수 ÷ 24 비율로 낮춰 계산합니다(18K = 18/24, 14K = 14/24).",
      "aboutP2": "이 페이지는 국제 시세를 환산한 값이며, 금은방 판매가가 아닙니다. 실제 금은방의 매수·매도 가격에는 부가가치세와 판매 마진이 더해지고, 매장마다도 차이가 있습니다.",
      "unavailable": "실시간 금 시세 또는 환율을 지금 불러올 수 없어 계산 결과를 표시할 수 없습니다.",
      "footer": "표시된 가격은 정보 제공 목적으로만 제공되며, 투자 또는 구매 권유가 아닙니다."
    },
    "ja": {
      "title": "金価格計算機 — グラム・ドン(韓国の単位)換算",
      "description": "国際金価格をグラム単価、ドン(韓国の金の単位、1ドン=3.75g)単価に換算します。24K・18K・14Kの純度別価格も、リアルタイムの金先物価格とドル円レートから計算します。",
      "h1": "金価格計算機",
      "sub": "国際金価格 → グラム単価・ドン単価をリアルタイム換算",
      "formHeading": "計算する",
      "gramLabel": "重さ(グラム)",
      "donLabel": "重さ(ドン、1ドン=3.75g)",
      "karatLabel": "純度",
      "resultHeading": "計算結果",
      "forWeight": "{N}の価格",
      "perGramLabel": "1gあたり",
      "perDonLabel": "1ドン(3.75g)あたり",
      "basisHeading": "この価格について",
      "basisNote": "この金額は国際金価格(COMEX金先物)をリアルタイムのドル円レートで換算した国際相場ベースの参考値であり、宝飾店の販売価格ではありません。実店舗での購入時にはここに消費税や販売マージンが上乗せされるため、実際の購入価格はこの金額より高くなります。",
      "presetHeading": "ドン単位で見る",
      "presetLink": "{N}ドン",
      "donPageTitle": "金{N}ドンの価格 — 今いくら?",
      "donPageDescription": "金{N}ドン(韓国の単位、1ドン=3.75g)が今いくらか、国際金価格をリアルタイムで換算し、24K・18K・14Kの純度別に表示します。",
      "aboutHeading": "計算方法について",
      "aboutP1": "1gあたりの価格は、COMEX金先物価格(GC=F、1トロイオンスあたりの米ドル)を1オンス=31.1034768gで割り、リアルタイムのドル円レートで換算した値です。1ドンあたりの価格は1g価格の3.75倍です。24K未満の純度はカラット数÷24の比率で価格を下げて計算します(18K=18/24、14K=14/24)。",
      "aboutP2": "このページは国際相場を換算した参考値であり、宝飾店の販売価格ではありません。実際の店舗での売買価格には消費税と販売マージンが上乗せされ、店舗ごとにも差があります。",
      "unavailable": "金価格または為替レートを現在取得できないため、計算結果を表示できません。",
      "footer": "表示価格は情報提供のみを目的としており、投資や購入の助言ではありません。"
    }
  },
  "movers": {
    "en": {
      "title": "Daily Movers — Today's Gainers & Losers",
      "description": "The biggest movers today across US, Japanese and Korean stocks and the top cryptocurrencies, with a heatmap of the tape.",
      "h1": "Daily Movers",
      "sub": "Gainers · losers · heatmap",
      "heatmapHeading": "Heatmap",
      "gainersHeading": "Top Gainers",
      "losersHeading": "Top Losers",
      "equitiesHeading": "Equities",
      "cryptoHeading": "Crypto",
      "colName": "Name",
      "colLast": "Last",
      "colPct": "% Chg",
      "aboutHeading": "About This Page",
      "aboutP": "Ranked on the move against the previous close, across the most liquid names on this desk. Markets in different time zones are open at different hours, so a quiet session in one region can leave its names clustered near zero while another region does the moving.",
      "unavailable": "Live data is not available right now, so today's ranking cannot be shown.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "오늘의 급등락 종목 — 상승률·하락률 상위",
      "description": "미국·일본·한국 증시의 주요 종목과 시가총액 상위 가상자산 가운데 전일 대비 등락률이 가장 큰 종목을 정리했습니다. 상승률·하락률 상위 종목과 시장 흐름을 한눈에 보여주는 히트맵을 함께 제공합니다.",
      "h1": "오늘의 급등락 종목",
      "sub": "상승률 · 하락률 · 히트맵",
      "heatmapHeading": "히트맵",
      "gainersHeading": "상승률 상위",
      "losersHeading": "하락률 상위",
      "equitiesHeading": "주식",
      "cryptoHeading": "가상자산",
      "colName": "종목명",
      "colLast": "현재가",
      "colPct": "등락률",
      "aboutHeading": "페이지 안내",
      "aboutP": "이 페이지에서는 거래가 가장 활발한 종목을 대상으로 전일 대비 등락률 순으로 순위를 매깁니다. 지역마다 시차가 있어 증시 개장 시간이 다르기 때문에, 한 지역 증시가 한산한 날에는 해당 종목들의 등락률이 0% 부근에 몰리고 그사이 다른 지역 종목들이 상승률·하락률 상위를 채우기도 합니다.",
      "unavailable": "현재 실시간 시세를 불러올 수 없어 오늘의 급등락 순위를 표시할 수 없습니다.",
      "footer": "시세 정보는 지연될 수 있으며, 투자 자문이 아닌 정보 제공을 목적으로 합니다."
    },
    "ja": {
      "title": "本日の値上がり・値下がりランキング｜米国・日本・韓国株と暗号資産",
      "description": "米国株・日本株・韓国株と主要な暗号資産を対象に、本日の値上がり率・値下がり率の上位銘柄を掲載します。前日終値を基準とした騰落率でランキング化し、ヒートマップで市場全体の値動きも一目で把握できます。銘柄比較にもご活用ください。",
      "h1": "本日の値動きランキング",
      "sub": "値上がり・値下がり・ヒートマップ",
      "heatmapHeading": "ヒートマップ",
      "gainersHeading": "値上がり率上位",
      "losersHeading": "値下がり率上位",
      "equitiesHeading": "株式",
      "cryptoHeading": "暗号資産",
      "colName": "銘柄",
      "colLast": "現在値",
      "colPct": "騰落率",
      "aboutHeading": "このページについて",
      "aboutP": "当サイトが取り扱う流動性の高い銘柄を対象に、前日終値からの騰落率で順位付けしています。地域によって取引時間帯が異なるため、ある市場が閑散としている日は、その地域の銘柄の騰落率がゼロ付近に集中し、上位・下位が別の地域の銘柄で占められることもあります。",
      "unavailable": "現在、リアルタイムデータを取得できないため、本日のランキングを表示できません。",
      "footer": "市場データには遅延が生じる場合があります。情報提供のみを目的としており、投資助言ではありません。"
    }
  },
  "search": {
    "en": {
      "title": "Search — Stocks, Crypto, FX and Tools",
      "description": "Search every quote page, currency pair, comparison and tool on PNL404. Results filter as you type.",
      "h1": "Search",
      "sub": "Quotes, currencies, comparisons and tools",
      "placeholder": "Search a ticker, company, currency or tool",
      "noResults": "Nothing matched that. Try a ticker, a company name or a currency code.",
      "emptyPrompt": "Start typing to search across every page on the desk.",
      "resultsCount": "{n} results",
      "browseHeading": "Browse",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "통합 검색 — 주식·코인·환율 시세와 투자 도구",
      "description": "PNL404에 있는 모든 주식·코인 시세 페이지와 환율, 종목 비교, 투자 도구를 한 곳에서 검색할 수 있습니다. 티커나 회사명, 통화 코드를 입력하면 검색 결과가 실시간으로 좁혀집니다.",
      "h1": "검색",
      "sub": "시세, 환율, 종목 비교, 투자 도구",
      "placeholder": "티커, 회사명, 통화, 도구 검색",
      "noResults": "검색 결과가 없습니다. 티커나 회사명, 통화 코드로 다시 검색해 보세요.",
      "emptyPrompt": "검색어를 입력하시면 PNL404의 모든 페이지에서 결과를 바로 찾아 드립니다.",
      "resultsCount": "검색 결과 {n}건",
      "browseHeading": "둘러보기",
      "footer": "시세 정보는 지연될 수 있으며, 투자 자문이 아닌 단순 정보 제공을 목적으로 합니다."
    },
    "ja": {
      "title": "サイト内検索｜株価・仮想通貨・為替・投資ツール",
      "description": "PNL404に掲載しているすべての株価ページ、通貨ペア、銘柄比較、投資ツールをまとめて検索できます。ティッカーや企業名、通貨コードを入力すると、その場で候補が絞り込まれ、目的のページにすぐたどり着けます。",
      "h1": "サイト内検索",
      "sub": "株価・為替・銘柄比較・投資ツール",
      "placeholder": "ティッカー・企業名・通貨・ツール名で検索",
      "noResults": "該当する項目が見つかりませんでした。ティッカーや企業名、通貨コードでお試しください。",
      "emptyPrompt": "キーワードを入力すると、サイト内のすべてのページから検索できます。",
      "resultsCount": "検索結果{n}件",
      "browseHeading": "一覧から探す",
      "footer": "市場データは遅延する場合があります。情報提供を目的としたものであり、投資助言ではありません。"
    }
  },
  "widget": {
    "en": {
      "title": "Free Embeddable Market Ticker Widget",
      "description": "Put a live stock, crypto and FX ticker on your own site. Pick your symbols, copy the iframe, done — no key and no signup.",
      "h1": "Ticker Widget",
      "sub": "Pick symbols · copy the iframe · drop it on any page",
      "previewHeading": "Preview",
      "symbolsHeading": "Symbols",
      "symbolsNote": "Up to 8",
      "snippetHeading": "Embed Code",
      "copyButton": "Copy embed code",
      "copiedButton": "Copied",
      "openEmbed": "Open the widget",
      "resetButton": "Reset",
      "aboutHeading": "How It Works",
      "aboutP": "The iframe loads a lightweight strip that refreshes on its own, with no script to install, no API key and no signup. It inherits nothing from your page's styles, so it looks the same everywhere. Attribution back to this site is appreciated but not required.",
      "emptyNote": "Pick at least one symbol.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "내 사이트에 붙이는 무료 실시간 시세 티커 위젯 (주식·코인·환율)",
      "description": "주식·코인·환율 실시간 시세 티커를 내 사이트에 바로 붙일 수 있습니다. 원하는 종목을 최대 8개까지 고른 뒤 iframe 코드만 복사해 넣으면 끝입니다. API 키도 회원가입도 필요 없고 시세는 자동으로 갱신됩니다.",
      "h1": "시세 티커 위젯",
      "sub": "종목 선택 · iframe 복사 · 어느 페이지에나 붙여넣기",
      "previewHeading": "미리보기",
      "symbolsHeading": "종목",
      "symbolsNote": "최대 8개",
      "snippetHeading": "임베드 코드",
      "copyButton": "임베드 코드 복사",
      "copiedButton": "복사 완료",
      "openEmbed": "위젯 열기",
      "resetButton": "초기화",
      "aboutHeading": "작동 방식",
      "aboutP": "iframe을 넣으면 가벼운 시세 표시줄이 로드되어 별도 조작 없이 스스로 갱신됩니다. 설치할 스크립트도, API 키도, 회원가입도 필요 없습니다. 내 페이지의 스타일을 전혀 상속받지 않기 때문에 어느 사이트에 붙여도 똑같이 보입니다. 이 사이트로 연결되는 출처 링크를 남겨 주시면 감사하지만, 필수는 아닙니다.",
      "emptyNote": "종목을 하나 이상 선택해 주세요.",
      "footer": "시세 정보는 지연될 수 있으며, 투자 자문이 아닌 정보 제공을 목적으로 합니다."
    },
    "ja": {
      "title": "株価ティッカーウィジェット｜仮想通貨・為替対応｜無料で埋め込み",
      "description": "株価・仮想通貨・為替のティッカーを自分のサイトに無料で設置できるウィジェットです。銘柄を選んでiframeタグをコピーし、ページに貼り付けるだけです。APIキーも会員登録も不要で、値動きは自動で更新されます。最大8銘柄まで選べます。",
      "h1": "ティッカーウィジェット",
      "sub": "銘柄を選ぶ · iframeをコピー · 好きなページに貼る",
      "previewHeading": "プレビュー",
      "symbolsHeading": "銘柄",
      "symbolsNote": "最大8銘柄",
      "snippetHeading": "埋め込みコード",
      "copyButton": "コードをコピー",
      "copiedButton": "コピー完了",
      "openEmbed": "ウィジェットを開く",
      "resetButton": "リセット",
      "aboutHeading": "仕組み",
      "aboutP": "iframeが読み込むのは軽量なティッカーだけで、価格は自動で更新されます。スクリプトの設置もAPIキーも会員登録も必要ありません。設置したページのCSSの影響を受けないため、どのサイトでも同じ見た目で表示されます。当サイトへのリンクを添えていただけると励みになりますが、必須ではありません。",
      "emptyNote": "銘柄を1つ以上選んでください。",
      "footer": "市場データは遅延する場合があります。本情報は情報提供のみを目的としたものであり、投資助言ではありません。"
    }
  }
};
