import type { HomeCopyBundle } from "./home-copy";

// GENERATED - do not edit by hand.

export const HOME_COPY: HomeCopyBundle = {
  "home": {
    "en": {
      "title": "PNL404 — Global Markets, One Page",
      "description": "Live US, Japanese and Korean stocks, top cryptocurrencies, FX and commodities — with the latest market headlines, on a single page. Profit not found; everything else is.",
      "tagline": "Profit Not Found — Global Markets, One Page",
      "updated": "Updated {time} UTC",
      "navAria": "Markets",
      "navUs": "U.S.",
      "navJapan": "Japan",
      "navKorea": "Korea",
      "navCrypto": "Crypto",
      "navKimchi": "Kimchi Premium",
      "navFearGreed": "Fear & Greed",
      "navCurrencies": "Currencies",
      "navMovers": "Movers",
      "navCompare": "Compare",
      "navInvested": "If I Had Invested",
      "navQuotes": "All Quotes",
      "navSearch": "Search",
      "sampleNote": "Note: {parts} shown here are sample figures — live feeds connect automatically in production deployments.",
      "samplePartQuotes": "market quotes",
      "samplePartCrypto": "crypto prices",
      "samplePartNews": "headlines",
      "cryptoHeading": "Cryptocurrencies",
      "cryptoLiveNote": "streaming tick-by-tick",
      "cryptoStaticNote": "Top 10 by market cap · 24/7",
      "totalMarketCap": "Total market cap",
      "change24h": "(24h)",
      "btcDominance": "Bitcoin dominance",
      "kimchiLink": "Kimchi premium",
      "fearGreedLink": "Fear & Greed",
      "glanceHeading": "Markets at a Glance",
      "equitiesHeading": "Equities",
      "equitiesNote": "Large caps by market",
      "regionUsTitle": "United States",
      "regionUsVenue": "NYSE · Nasdaq",
      "regionJapanTitle": "Japan",
      "regionJapanVenue": "Tokyo Stock Exchange",
      "regionKoreaTitle": "South Korea",
      "regionKoreaVenue": "Korea Exchange",
      "fxHeading": "Currencies & Commodities",
      "fxNote": "Currency converter",
      "newsHeading": "Latest Headlines",
      "newsCatCrypto": "Crypto",
      "newsCatStock": "Markets",
      "newsCatEconomy": "Economy",
      "tradeHeading": "Where to Trade",
      "colCompany": "Company",
      "colLast": "Last",
      "colChg": "Chg",
      "colChgPct": "% Chg",
      "colName": "Name",
      "colPrice": "Price",
      "col24h": "24h",
      "colMktCap": "Mkt Cap"
    },
    "ko": {
      "title": "PNL404 — 나스닥·코스피·코인 실시간 시세 한 페이지",
      "description": "나스닥·닛케이·코스피 대형주부터 시가총액 상위 코인, 환율과 원자재까지 실시간 시세를 한 페이지에 모았습니다. 최신 시장 헤드라인도 함께 제공합니다. 수익은 찾을 수 없어도 나머지는 모두 있습니다.",
      "tagline": "수익은 찾을 수 없습니다 — 글로벌 마켓, 한 페이지에",
      "updated": "{time} UTC 기준 업데이트",
      "navAria": "마켓",
      "navUs": "미국",
      "navJapan": "일본",
      "navKorea": "한국",
      "navCrypto": "코인",
      "navKimchi": "김치프리미엄",
      "navFearGreed": "공포탐욕지수",
      "navCurrencies": "환율",
      "navMovers": "급등락",
      "navCompare": "종목비교",
      "navInvested": "그때 샀다면",
      "navQuotes": "전체 시세",
      "navSearch": "검색",
      "sampleNote": "참고: 이 페이지의 {parts} 데이터는 샘플 수치이며, 실제 서비스 환경에서는 실시간 피드가 자동으로 연결됩니다.",
      "samplePartQuotes": "증시 시세",
      "samplePartCrypto": "코인 시세",
      "samplePartNews": "헤드라인",
      "cryptoHeading": "가상자산",
      "cryptoLiveNote": "틱 단위 실시간 스트리밍",
      "cryptoStaticNote": "시가총액 상위 10개 · 연중무휴 24시간 거래",
      "totalMarketCap": "총 시가총액",
      "change24h": "(24시간)",
      "btcDominance": "비트코인 도미넌스",
      "kimchiLink": "김치프리미엄",
      "fearGreedLink": "공포탐욕지수",
      "glanceHeading": "시장 한눈에 보기",
      "equitiesHeading": "증시",
      "equitiesNote": "시장별 대형주",
      "regionUsTitle": "미국",
      "regionUsVenue": "NYSE · 나스닥",
      "regionJapanTitle": "일본",
      "regionJapanVenue": "도쿄증권거래소",
      "regionKoreaTitle": "한국",
      "regionKoreaVenue": "한국거래소",
      "fxHeading": "환율·원자재",
      "fxNote": "환율 계산기",
      "newsHeading": "최신 헤드라인",
      "newsCatCrypto": "코인",
      "newsCatStock": "증시",
      "newsCatEconomy": "경제",
      "tradeHeading": "거래 플랫폼 안내",
      "colCompany": "종목",
      "colLast": "현재가",
      "colChg": "전일 대비",
      "colChgPct": "등락률",
      "colName": "코인명",
      "colPrice": "현재가",
      "col24h": "24시간",
      "colMktCap": "시가총액"
    },
    "ja": {
      "title": "PNL404 — 米国・日本・韓国株、仮想通貨、為替を1ページで",
      "description": "米国・日本・韓国の株価をリアルタイムで表示し、時価総額上位の仮想通貨、為替、商品市況、最新の市場ヘッドラインまで1ページに集約しました。利益は見つかりませんが、それ以外はすべてここにあります。",
      "tagline": "利益は見つかりません — 世界の市場を1ページで",
      "updated": "{time} UTC 更新",
      "navAria": "マーケット",
      "navUs": "米国",
      "navJapan": "日本",
      "navKorea": "韓国",
      "navCrypto": "仮想通貨",
      "navKimchi": "キムチプレミアム",
      "navFearGreed": "恐怖・強欲",
      "navCurrencies": "為替",
      "navMovers": "値動き",
      "navCompare": "銘柄比較",
      "navInvested": "リターン試算",
      "navQuotes": "全銘柄一覧",
      "navSearch": "検索",
      "sampleNote": "※ ここに表示されている{parts}はサンプルデータです。本番環境では自動的にリアルタイムデータに接続されます。",
      "samplePartQuotes": "株価",
      "samplePartCrypto": "仮想通貨価格",
      "samplePartNews": "ヘッドライン",
      "cryptoHeading": "仮想通貨",
      "cryptoLiveNote": "リアルタイム配信中",
      "cryptoStaticNote": "時価総額トップ10・24時間365日",
      "totalMarketCap": "時価総額合計",
      "change24h": "（24時間）",
      "btcDominance": "BTCドミナンス",
      "kimchiLink": "キムチプレミアム",
      "fearGreedLink": "恐怖・強欲指数",
      "glanceHeading": "マーケット概況",
      "equitiesHeading": "株式",
      "equitiesNote": "市場別の大型株",
      "regionUsTitle": "米国",
      "regionUsVenue": "NYSE・ナスダック",
      "regionJapanTitle": "日本",
      "regionJapanVenue": "東京証券取引所",
      "regionKoreaTitle": "韓国",
      "regionKoreaVenue": "韓国取引所",
      "fxHeading": "為替・商品",
      "fxNote": "通貨換算ツール",
      "newsHeading": "最新ヘッドライン",
      "newsCatCrypto": "仮想通貨",
      "newsCatStock": "マーケット",
      "newsCatEconomy": "経済",
      "tradeHeading": "取引所・証券会社",
      "colCompany": "銘柄",
      "colLast": "現在値",
      "colChg": "前日比",
      "colChgPct": "騰落率",
      "colName": "銘柄名",
      "colPrice": "価格",
      "col24h": "24時間",
      "colMktCap": "時価総額"
    }
  },
  "pulse": {
    "en": {
      "title": "{QUERY}",
      "description": "{QUERY} — live figures, a short explainer and the pages that answer it next, on PNL404.",
      "hubTitle": "Market Questions, Answered",
      "hubDescription": "Short, current answers to the questions people actually ask about crypto, stocks and exchange rates — each with live figures and where to look next.",
      "hubH1": "Questions",
      "hubSub": "{n} answers",
      "faqHeading": "Frequently Asked",
      "relatedQuotesHeading": "Live Prices",
      "relatedConvertHeading": "Converters",
      "relatedHubsHeading": "Go Deeper",
      "popularHeading": "More Questions",
      "updatedNote": "Figures on this page update automatically.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "{QUERY}",
      "description": "{QUERY} — 실시간 시세와 짧은 해설, 이어서 볼 페이지까지 PNL404에서 한눈에 정리했습니다.",
      "hubTitle": "시장 궁금증, 바로 답합니다",
      "hubDescription": "암호화폐와 주식, 환율까지 투자자들이 실제로 궁금해하는 질문에 최신 수치로 짧게 답합니다. 질문마다 실시간 시세와 다음에 볼 페이지를 함께 담았습니다.",
      "hubH1": "시장 궁금증",
      "hubSub": "답변 {n}개",
      "faqHeading": "자주 묻는 질문",
      "relatedQuotesHeading": "실시간 시세",
      "relatedConvertHeading": "계산기",
      "relatedHubsHeading": "더 알아보기",
      "popularHeading": "질문 더 보기",
      "updatedNote": "이 페이지의 수치는 자동으로 갱신됩니다.",
      "footer": "시세 정보는 지연될 수 있으며, 투자 권유가 아닌 정보 제공을 목적으로 합니다."
    },
    "ja": {
      "title": "{QUERY}",
      "description": "{QUERY}という疑問に、PNL404がお答えします。リアルタイムの数値と短い解説、次に読むべき関連ページをまとめました。",
      "hubTitle": "相場の疑問に答えます",
      "hubDescription": "仮想通貨や株式、為替について実際によく検索される疑問に、短く最新の情報でお答えします。各ページにリアルタイムの数値と、次に見るべきページへの案内を添えています。",
      "hubH1": "相場の疑問",
      "hubSub": "{n}件の回答",
      "faqHeading": "よくある質問",
      "relatedQuotesHeading": "最新価格",
      "relatedConvertHeading": "換算ツール",
      "relatedHubsHeading": "もっと詳しく",
      "popularHeading": "他の質問",
      "updatedNote": "このページの数値は自動で更新されます。",
      "footer": "相場データは遅延する場合があります。情報提供のみを目的としており、投資助言ではありません。"
    }
  }
};
