import type { MarketHoursCopy } from "./market-hours-copy";

// GENERATED - do not edit by hand.

export const MARKET_HOURS_COPY: Record<"en" | "ko" | "ja", MarketHoursCopy> = {
  en: {
    marketName: {
      us: "US Markets (NYSE · Nasdaq)",
      korea: "Korea Markets (KRX · Nextrade)",
      japan: "Japan Markets (TSE)",
      crypto: "Crypto",
      fx: "Forex (FX)",
    },
    sessionLabel: {
      regular: "Regular session",
      afterhours: "After-market",
      premarket: "Pre-market",
      main: "Main session",
      morning: "Morning session",
      afternoon: "Afternoon session",
      always: "Always open",
      week: "FX week",
    },
    statusOpenNow: "Open now",
    statusClosedNow: "Closed now",
    closesIn: "Closes in {T}",
    opensIn: "Opens in {T}",
    holidayToday: "Closed today for {NAME}",
    earlyCloseToday: "Early close today at {TIME}",
    asOf: "as of",
    hubTitle: "Market Hours — Is the Market Open Right Now?",
    hubDescription: "Live open/closed status for US, Korean and Japanese stock markets, crypto and forex, with countdowns to the next open or close and every market's holiday calendar.",
    hubH1: "Market Hours",
    hubSub: "Live open/closed status across every market on this desk",
    colMarket: "Market",
    colStatus: "Status",
    colHours: "Hours",
    colNext: "Next",
    marketTitle: "{MARKET} Hours — Open/Closed, Sessions & Holidays",
    marketDescription: "Live open/closed status for {MARKET}, every trading session, upcoming holidays, and a subscribable holiday calendar.",
    sessionsHeading: "Trading Sessions",
    upcomingHolidaysHeading: "Upcoming Holidays",
    noUpcomingHolidays: "No published holidays in the coming months.",
    centralBankHeading: { us: "Next FOMC Meeting", korea: "Next BOK Rate Decision", japan: "Next BOJ Meeting" },
    noUpcomingMeeting: "Not yet announced.",
    calendarHeading: "Subscribe to This Calendar",
    addToCalendar: "Add to calendar (.ics)",
    holidayYearLink: "Full {YEAR} holiday list →",
    koreaExtensionNote: "From 2026-09-14, KRX adds a 16:00–20:00 after-market session alongside the unchanged 09:00–15:30 main session.",
    koreaPremarketNote: "A planned 07:00–07:50 pre-market session has been postponed again, now targeted for end of 2027.",
    aboutHeading: "About These Hours",
    aboutP: "Times are the exchange's own published sessions and holiday calendar. A shortened trading day (early close) is shown as such, not as a full holiday.",
    quickTitle: "Is the Stock Market Open Today?",
    quickDescription: "Live open/closed status for the US stock market (NYSE/Nasdaq) right now, plus Korea and Japan.",
    quickH1: "Is the Market Open Today?",
    quickYes: "Yes — the market is open right now.",
    quickNo: "No — the market is closed right now.",
    otherMarketsHeading: "Other Markets",
    holidayYearTitle: "{MARKET} Holidays {YEAR} — Full Market Closure Calendar",
    holidayYearDescription: "Every day {MARKET} is closed in {YEAR}, plus early closes, sourced from the exchange's own published calendar.",
    holidayYearH1: "{MARKET} Holidays {YEAR}",
    colDate: "Date",
    colDay: "Day",
    colHoliday: "Holiday",
    colType: "Type",
    fullClosureLabel: "Closed",
    earlyCloseLabel: "Early close",
    notYetAnnounced: "{MARKET} has not yet published its {YEAR} holiday calendar.",
    otherYearsHeading: "Other Years",
    footer: "Trading hours and holidays are the exchange's own published schedule and may change without notice. Not investment advice.",
  },
  ko: {
    marketName: {
      us: "미국 증시(뉴욕증권거래소·나스닥)",
      korea: "한국 증시(코스피·코스닥·넥스트레이드)",
      japan: "일본 증시(도쿄증권거래소)",
      crypto: "암호화폐",
      fx: "외환(FX)",
    },
    sessionLabel: {
      regular: "정규장",
      afterhours: "애프터마켓",
      premarket: "프리마켓",
      main: "메인마켓",
      morning: "오전장",
      afternoon: "오후장",
      always: "24시간 상시 거래",
      week: "외환 거래 주간",
    },
    statusOpenNow: "지금 개장 중",
    statusClosedNow: "지금 휴장 중",
    closesIn: "{T} 후 마감",
    opensIn: "{T} 후 개장",
    holidayToday: "오늘은 {NAME}(으)로 휴장입니다",
    earlyCloseToday: "오늘은 {TIME}에 조기 마감합니다",
    asOf: "기준",
    hubTitle: "증시 개장시간 — 지금 개장 중인 시장은?",
    hubDescription: "미국·한국·일본 증시와 암호화폐, 외환 시장의 실시간 개장·휴장 상태를 한 페이지에서 확인하세요. 다음 개장·마감까지 남은 시간과 각 시장의 휴장일 캘린더도 함께 제공합니다.",
    hubH1: "증시 개장시간",
    hubSub: "전 세계 시장의 실시간 개장·휴장 상태",
    colMarket: "시장",
    colStatus: "상태",
    colHours: "거래시간",
    colNext: "다음 일정",
    marketTitle: "{MARKET} 개장시간 — 거래시간·휴장일 안내",
    marketDescription: "{MARKET}의 실시간 개장·휴장 상태와 거래시간, 다가오는 휴장일, 구독 가능한 휴장일 캘린더를 제공합니다.",
    sessionsHeading: "거래시간",
    upcomingHolidaysHeading: "다가오는 휴장일",
    noUpcomingHolidays: "앞으로 몇 달간 공표된 휴장일이 없습니다.",
    centralBankHeading: { us: "다음 FOMC 회의", korea: "다음 금통위 통화정책방향 결정회의", japan: "다음 일본은행 금융정책결정회의" },
    noUpcomingMeeting: "아직 일정이 발표되지 않았습니다.",
    calendarHeading: "캘린더 구독하기",
    addToCalendar: "캘린더에 추가(.ics)",
    holidayYearLink: "{YEAR}년 휴장일 전체 보기 →",
    koreaExtensionNote: "2026년 9월 14일부터 기존 정규장(09:00~15:30)은 그대로 유지되고, 애프터마켓(16:00~20:00)이 새로 도입됩니다.",
    koreaPremarketNote: "함께 추진되던 프리마켓(07:00~07:50)은 다시 연기되어, 현재 2027년 말 도입을 목표로 하고 있습니다.",
    aboutHeading: "이 페이지 안내",
    aboutP: "거래시간은 각 거래소가 직접 공표한 정규 일정과 휴장일 캘린더를 기준으로 합니다. 조기 마감일은 전일 휴장이 아니라 단축 거래일로 별도 표시합니다.",
    quickTitle: "오늘 증시 개장하나요? (미국 증시 개장 여부)",
    quickDescription: "미국 증시(뉴욕증권거래소·나스닥)의 실시간 개장·휴장 상태와, 한국·일본 증시 상태까지 함께 확인하세요.",
    quickH1: "오늘 증시가 열렸나요?",
    quickYes: "네, 지금 개장 중입니다.",
    quickNo: "아니요, 지금은 휴장입니다.",
    otherMarketsHeading: "다른 시장 보기",
    holidayYearTitle: "{MARKET} {YEAR}년 휴장일 — 전체 휴장 캘린더",
    holidayYearDescription: "{YEAR}년 {MARKET}이(가) 휴장하는 모든 날짜와 조기 마감일을, 거래소가 직접 공표한 일정을 기준으로 정리했습니다.",
    holidayYearH1: "{MARKET} {YEAR}년 휴장일",
    colDate: "날짜",
    colDay: "요일",
    colHoliday: "휴장 사유",
    colType: "구분",
    fullClosureLabel: "휴장",
    earlyCloseLabel: "조기 마감",
    notYetAnnounced: "{MARKET}은(는) 아직 {YEAR}년 휴장일 일정을 발표하지 않았습니다.",
    otherYearsHeading: "다른 연도 보기",
    footer: "거래시간과 휴장일은 각 거래소가 공표한 일정이며 사전 예고 없이 변경될 수 있습니다. 투자 자문이 아닙니다.",
  },
  ja: {
    marketName: {
      us: "米国株式市場(NYSE・ナスダック)",
      korea: "韓国株式市場(KOSPI・KOSDAQ・Nextrade)",
      japan: "日本株式市場(東証)",
      crypto: "暗号資産",
      fx: "外国為替(FX)",
    },
    sessionLabel: {
      regular: "通常取引",
      afterhours: "アフター・マーケット",
      premarket: "プレ・マーケット",
      main: "メインマーケット",
      morning: "前場",
      afternoon: "後場",
      always: "24時間取引",
      week: "為替の週間取引",
    },
    statusOpenNow: "現在取引中",
    statusClosedNow: "現在休場中",
    closesIn: "あと{T}で終了",
    opensIn: "あと{T}で開始",
    holidayToday: "本日は{NAME}のため休場です",
    earlyCloseToday: "本日は{TIME}に短縮取引で終了します",
    asOf: "時点",
    hubTitle: "証券取引所の取引時間 — 今どの市場が開いている?",
    hubDescription: "米国・韓国・日本の株式市場と暗号資産、外国為替市場のリアルタイムの開場・休場状況を1ページで確認できます。次の開場・終了までの残り時間と、各市場の休場カレンダーも掲載しています。",
    hubH1: "証券取引所の取引時間",
    hubSub: "世界の市場のリアルタイム開場・休場状況",
    colMarket: "市場",
    colStatus: "状態",
    colHours: "取引時間",
    colNext: "次の予定",
    marketTitle: "{MARKET}の取引時間 — セッション・休場日ガイド",
    marketDescription: "{MARKET}のリアルタイムの開場・休場状況、取引セッション、今後の休場日、購読できる休場カレンダーを掲載しています。",
    sessionsHeading: "取引セッション",
    upcomingHolidaysHeading: "今後の休場日",
    noUpcomingHolidays: "今後数か月の公表済み休場日はありません。",
    centralBankHeading: { us: "次回FOMC会合", korea: "次回韓国銀行 金融通貨委員会", japan: "次回日銀 金融政策決定会合" },
    noUpcomingMeeting: "まだ日程が発表されていません。",
    calendarHeading: "カレンダーを購読",
    addToCalendar: "カレンダーに追加(.ics)",
    holidayYearLink: "{YEAR}年の休場日一覧を見る →",
    koreaExtensionNote: "2026年9月14日から、既存のメインセッション(09:00〜15:30)はそのままに、アフター・マーケット(16:00〜20:00)が新たに導入されます。",
    koreaPremarketNote: "同時に検討されていたプレ・マーケット(07:00〜07:50)は再び延期され、現在は2027年末の導入を目指しています。",
    aboutHeading: "このページについて",
    aboutP: "取引時間は各取引所が公表している正規のスケジュールと休場カレンダーに基づいています。短縮取引日は全休場日とは区別して表示しています。",
    quickTitle: "米国株式市場は今日開いている?",
    quickDescription: "米国株式市場(NYSE・ナスダック)のリアルタイムの開場・休場状況に加え、韓国・日本市場の状況もあわせて確認できます。",
    quickH1: "市場は今日開いている?",
    quickYes: "はい、現在取引中です。",
    quickNo: "いいえ、現在休場中です。",
    otherMarketsHeading: "他の市場を見る",
    holidayYearTitle: "{MARKET} {YEAR}年 休場日 — 休場カレンダー一覧",
    holidayYearDescription: "{YEAR}年に{MARKET}が休場するすべての日と短縮取引日を、取引所が公表しているスケジュールをもとにまとめました。",
    holidayYearH1: "{MARKET} {YEAR}年の休場日",
    colDate: "日付",
    colDay: "曜日",
    colHoliday: "休場理由",
    colType: "区分",
    fullClosureLabel: "休場",
    earlyCloseLabel: "短縮取引",
    notYetAnnounced: "{MARKET}は{YEAR}年の休場日スケジュールをまだ発表していません。",
    otherYearsHeading: "他の年を見る",
    footer: "取引時間・休場日は各取引所が公表しているスケジュールであり、予告なく変更される場合があります。投資助言ではありません。",
  },
};
