import type { PageCopy } from "./page-copy";

// GENERATED - do not edit by hand. Korean and Japanese copy was localized by a
// writer pass and corrected by a native financial-editor pass.

export const PAGE_COPY: PageCopy = {
  "kimchi": {
    "en": {
      "title": "Kimchi Premium Tracker",
      "description": "Live kimchi premium for Bitcoin and top altcoins — the price gap between Korea's Upbit exchange and global markets, updated every 30 seconds.",
      "h1": "Kimchi Premium",
      "sub": "Korea's crypto price gap · Upbit vs global markets · updated {time} UTC",
      "rightNow": "Right Now",
      "btcPremium": "Bitcoin premium",
      "avgPremium": "Average premium · {n} coins",
      "usdKrw": "USD/KRW",
      "byCoin": "By Coin",
      "byCoinNote": "Upbit KRW vs global USD",
      "colCoin": "Coin",
      "colUpbit": "Upbit (KRW)",
      "colGlobal": "Global (USD)",
      "colGlobalKrw": "Global → KRW",
      "colPremium": "Premium",
      "whatIsHeading": "What Is the Kimchi Premium?",
      "whatIsP1": "The kimchi premium is the gap between cryptocurrency prices on South Korean exchanges and prices on global markets. When Bitcoin trades at a 3% premium, Korean buyers on Upbit are paying 3% more won-for-won than buyers elsewhere are paying in dollars. A negative reading — Koreans call it the reverse premium (역프리미엄) — means coins are cheaper in Korea.",
      "whatIsP2": "The gap exists because arbitrage is hard to execute against the Korean won. Korea's capital controls limit how much money can move across the border, exchanges require verified local bank accounts held by Korean residents, and transfer rules add friction to moving coins between venues. So when Korean retail demand surges, local prices can run ahead of the world's — and stay there. Historically the premium has swung from above 50% at the peak of the 2017–2018 frenzy to negative territory in bear markets, which makes it a widely-watched gauge of Korean retail sentiment.",
      "howHeading": "How We Calculate It",
      "howP": "For each coin: premium = Upbit price (KRW) ÷ (global price (USD) × USD/KRW) − 1. Upbit prices come from Upbit's public API, global dollar prices from Coinbase trade data (CoinGecko's global average as fallback), and the USD/KRW rate from live FX data. Figures refresh automatically every 30 seconds. This is information, not investment advice — executing this arbitrage in practice involves regulatory, banking and transfer constraints.",
      "tradeHeading": "Trade Crypto",
      "partnerOffers": "Partner offers",
      "sampleNote": "Note: sample figures shown — live data connects automatically in production deployments.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "김치프리미엄 실시간 – 업비트·해외 비트코인 가격 차이",
      "description": "비트코인과 주요 알트코인의 김치프리미엄을 실시간으로 제공합니다. 국내 업비트 시세와 해외 거래소 시세의 가격 차이를 원화로 환산해 30초마다 자동 갱신하며, 역프리미엄 전환 여부까지 한눈에 확인할 수 있습니다.",
      "h1": "김치프리미엄",
      "sub": "국내 코인 시세 격차 · 업비트와 해외 시장 비교 · {time} UTC 갱신",
      "rightNow": "실시간 현황",
      "btcPremium": "비트코인 프리미엄",
      "avgPremium": "평균 프리미엄 · 코인 {n}개",
      "usdKrw": "원·달러 환율",
      "byCoin": "코인별 프리미엄",
      "byCoinNote": "업비트 원화 시세와 해외 달러 시세 비교",
      "colCoin": "코인",
      "colUpbit": "업비트(원)",
      "colGlobal": "해외(달러)",
      "colGlobalKrw": "원화 환산가",
      "colPremium": "프리미엄",
      "whatIsHeading": "김치프리미엄이란?",
      "whatIsP1": "김치프리미엄은 국내 거래소의 가상자산 가격과 해외 시장 가격의 차이를 뜻합니다. 비트코인이 3% 프리미엄에 거래된다면, 업비트에서 원화로 매수하는 국내 투자자는 해외에서 달러로 매수하는 투자자보다 3% 비싸게 사는 셈입니다. 수치가 마이너스로 내려가면 국내 시세가 해외보다 싸다는 뜻이며, 이를 흔히 역프리미엄(역프)이라고 부릅니다.",
      "whatIsP2": "이런 격차가 생기는 이유는 원화 시장을 상대로 차익거래를 실행하기가 어렵기 때문입니다. 외환 규제로 국경을 넘나드는 자금 이동에 한도가 있고, 거래소 이용에는 국내 거주자 명의의 실명확인 입출금 계좌가 필요하며, 트래블룰 등 전송 규제까지 더해져 거래소 간 코인 이동에도 마찰이 생깁니다. 그래서 국내 개인 투자자 수요가 몰리면 국내 시세가 해외보다 앞서 나가고, 그 상태가 한동안 이어지기도 합니다. 실제로 2017~2018년 투자 광풍이 정점에 달했을 때는 프리미엄이 50%를 웃돌았고, 하락장에서는 마이너스로 돌아서기도 했습니다. 그만큼 국내 개인 투자 심리를 가늠하는 지표로 널리 활용됩니다.",
      "howHeading": "산출 방식",
      "howP": "코인별 프리미엄은 업비트 가격(원) ÷ (해외 가격(달러) × 원·달러 환율) − 1로 계산합니다. 업비트 가격은 업비트 공개 API, 해외 달러 가격은 코인베이스 체결 데이터(연결이 어려울 경우 코인게코의 글로벌 평균가로 대체), 원·달러 환율은 실시간 외환 데이터를 각각 사용합니다. 수치는 30초마다 자동으로 갱신됩니다. 본 자료는 정보 제공용이며 투자 권유가 아닙니다. 실제로 이 차익거래를 실행하려면 규제와 은행, 전송 관련 제약을 함께 고려해야 합니다.",
      "tradeHeading": "가상자산 거래하기",
      "partnerOffers": "제휴 혜택",
      "sampleNote": "참고: 현재 예시 수치가 표시되고 있습니다. 실제 서비스 환경에서는 실시간 데이터가 자동으로 연결됩니다.",
      "footer": "시세 정보는 지연될 수 있으며 참고용으로만 제공됩니다. 투자 권유가 아닙니다."
    },
    "ja": {
      "title": "キムチプレミアム リアルタイム｜韓国Upbitと海外の価格差",
      "description": "ビットコインと主要アルトコインのキムチプレミアムをリアルタイムで表示します。韓国のUpbit（アップビット）と海外市場の価格差を30秒ごとに自動更新し、ウォン換算した海外価格との乖離率を一覧で確認できます。",
      "h1": "キムチプレミアム",
      "sub": "韓国の暗号資産価格差 · Upbit vs 海外市場 · {time} UTC更新",
      "rightNow": "現在の状況",
      "btcPremium": "ビットコインのプレミアム",
      "avgPremium": "平均プレミアム · {n}銘柄",
      "usdKrw": "米ドル/ウォン",
      "byCoin": "銘柄別",
      "byCoinNote": "Upbitのウォン建て vs 海外のドル建て",
      "colCoin": "銘柄",
      "colUpbit": "Upbit（ウォン）",
      "colGlobal": "海外（ドル）",
      "colGlobalKrw": "海外（ウォン換算）",
      "colPremium": "プレミアム",
      "whatIsHeading": "キムチプレミアムとは",
      "whatIsP1": "キムチプレミアムとは、韓国の暗号資産取引所での価格と海外市場での価格との差を指します。ビットコインが3%のプレミアムで取引されている場合、Upbitで買う韓国の投資家は、海外でドル建てで買う投資家よりもウォン換算で3%高い価格を支払っていることになります。マイナスの場合は韓国のほうが割安であることを意味し、現地では「逆プレミアム」（역프리미엄）と呼ばれます。",
      "whatIsP2": "この価格差が生じるのは、韓国ウォンを介した裁定取引（アービトラージ）が実行しにくいためです。韓国では資本規制により国境をまたぐ資金移動が制限され、取引所の利用には韓国居住者本人名義の銀行口座の認証が必要で、送金ルールも取引所間のコイン移動の妨げになります。そのため韓国国内の個人投資家の需要が急増すると、現地価格が海外の水準を上回ったまま推移することがあります。過去には2017〜2018年の過熱局面で50%超まで拡大した一方、下落相場ではマイナス圏に沈んだこともあり、韓国の個人投資家心理を測る指標として広く注目されています。",
      "howHeading": "算出方法",
      "howP": "各銘柄のプレミアムは「Upbitの価格（ウォン）÷（海外価格（ドル）×米ドル/ウォンレート）−1」で算出します。Upbitの価格はUpbitの公開APIから、海外のドル建て価格はCoinbaseの約定データから（取得できない場合はCoinGeckoの全世界平均で代替）、米ドル/ウォンレートはリアルタイムの為替データからそれぞれ取得しています。数値は30秒ごとに自動更新されます。本ページは情報提供を目的としたものであり、投資助言ではありません。実際にこの裁定取引を行うには、規制・銀行・送金面での制約が伴います。",
      "tradeHeading": "暗号資産の取引",
      "partnerOffers": "提携先からのご案内",
      "sampleNote": "※ 表示中の数値はサンプルです。本番環境ではリアルタイムデータに自動接続されます。",
      "footer": "市場データは遅延する場合があります。情報提供のみを目的としており、投資助言ではありません。"
    }
  },
  "feargreed": {
    "en": {
      "title": "Crypto Fear & Greed Index",
      "description": "Live Crypto Fear & Greed Index — today's market sentiment score from 0 (extreme fear) to 100 (extreme greed), with yesterday, last week, last month and a 90-day history.",
      "h1": "Crypto Fear & Greed Index",
      "sub": "Market sentiment, 0–100 · updated {time} UTC",
      "todayHeading": "Today",
      "todayNote": "0 = extreme fear · 100 = extreme greed",
      "yesterday": "Yesterday",
      "lastWeek": "Last week",
      "lastMonth": "Last month",
      "historyHeading": "Last 90 Days",
      "extremeFear": "Extreme Fear",
      "fear": "Fear",
      "neutral": "Neutral",
      "greed": "Greed",
      "extremeGreed": "Extreme Greed",
      "howHeading": "How to Read It",
      "howP1": "The Crypto Fear & Greed Index compresses market sentiment into a single number between 0 and 100. Low readings mean investors are fearful — selling pressure, falling prices, nervous headlines. High readings mean greed: buying frenzies, parabolic charts, and the feeling that everyone is getting rich but you.",
      "howP2": "The score blends several inputs: price volatility, market momentum and volume, social media activity, Bitcoin's share of total market capitalization, and Google search trends. It is published once a day, so the number moves in daily steps rather than tick by tick.",
      "howP3": "The index is a contrarian tool by design. As the saying goes, be fearful when others are greedy and greedy when others are fearful — extreme fear has historically marked points where assets were oversold, and extreme greed points where a correction was due. It is a sentiment gauge, not a signal: it says how the crowd feels today, not what prices will do tomorrow.",
      "relatedPrefix": "Related: see the ",
      "kimchiLinkText": "kimchi premium",
      "relatedMiddle": " for how Korean retail demand compares with global prices, or the ",
      "cryptoLinkText": "crypto market page",
      "relatedSuffix": " for live prices.",
      "tradeHeading": "Trade Crypto",
      "partnerOffers": "Partner offers",
      "sampleNote": "Note: sample figures shown — live data connects automatically in production deployments.",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "코인 공포탐욕지수 실시간 — 오늘의 시장 심리 점수",
      "description": "실시간 코인 공포탐욕지수입니다. 0(극도의 공포)부터 100(극도의 탐욕)까지 오늘의 시장 심리 점수를 어제, 지난주, 지난달 수치와 함께 보여주고 최근 90일 추이도 확인할 수 있습니다.",
      "h1": "코인 공포탐욕지수",
      "sub": "시장 심리 0~100 · {time} UTC 기준 갱신(한국시간 +9시간)",
      "todayHeading": "오늘",
      "todayNote": "0 = 극도의 공포 · 100 = 극도의 탐욕",
      "yesterday": "전일",
      "lastWeek": "1주 전",
      "lastMonth": "1개월 전",
      "historyHeading": "최근 90일",
      "extremeFear": "극도의 공포",
      "fear": "공포",
      "neutral": "중립",
      "greed": "탐욕",
      "extremeGreed": "극도의 탐욕",
      "howHeading": "지수 읽는 법",
      "howP1": "코인 공포탐욕지수는 시장 심리를 0에서 100 사이의 숫자 하나로 압축한 지표입니다. 수치가 낮다는 것은 투자자들이 공포에 빠져 있다는 뜻으로, 매도 압력이 커지고 가격이 밀리며 불안한 헤드라인이 쏟아집니다. 수치가 높으면 탐욕 구간입니다. 매수세가 몰리고 차트가 수직으로 치솟으며, 나만 빼고 다들 돈을 버는 것 같은 기분이 듭니다.",
      "howP2": "점수는 여러 지표를 종합해 산출됩니다. 가격 변동성, 시장 모멘텀과 거래량, 소셜미디어 반응, 전체 시가총액에서 비트코인이 차지하는 비중, 구글 검색 트렌드가 함께 반영됩니다. 하루에 한 번 발표되기 때문에 지수는 틱 단위가 아니라 하루 단위로 움직입니다.",
      "howP3": "이 지수는 애초에 역발상 투자를 위해 만들어진 지표입니다. 남들이 탐욕스러울 때 두려워하고 남들이 두려워할 때 탐욕스러워지라는 말처럼, 역사적으로 극도의 공포 구간은 자산이 과매도된 지점인 경우가 많았고 극도의 탐욕 구간은 조정이 임박한 시점이었습니다. 다만 이는 심리를 재는 온도계일 뿐 매매 신호가 아닙니다. 오늘 군중이 어떤 기분인지 알려줄 뿐, 내일 가격이 어디로 갈지는 말해주지 않습니다.",
      "relatedPrefix": "함께 보기: 국내 개인 투자자 수요가 글로벌 시세와 얼마나 차이 나는지는",
      "kimchiLinkText": "김치프리미엄",
      "relatedMiddle": "지표에서, 실시간 시세는",
      "cryptoLinkText": "코인 시세 페이지",
      "relatedSuffix": "에서 확인할 수 있습니다.",
      "tradeHeading": "코인 거래하기",
      "partnerOffers": "제휴 혜택",
      "sampleNote": "안내: 예시 수치입니다. 실제 운영 환경에서는 실시간 데이터가 자동으로 연결됩니다.",
      "footer": "시세 정보는 지연될 수 있으며 참고용으로만 제공됩니다. 투자 자문이 아닙니다."
    },
    "ja": {
      "title": "暗号資産の恐怖・強欲指数｜リアルタイム市場心理",
      "description": "暗号資産の恐怖・強欲指数をリアルタイムで掲載。0（極度の恐怖）から100（極度の強欲）までの数値で本日の市場心理を示し、前日・1週間前・1カ月前との比較や過去90日間の推移も確認できます。極度の恐怖は売られすぎ、極度の強欲は過熱のサインとされます。",
      "h1": "暗号資産の恐怖・強欲指数",
      "sub": "市場心理を0～100で表示 · {time} UTC更新",
      "todayHeading": "本日",
      "todayNote": "0＝極度の恐怖 · 100＝極度の強欲",
      "yesterday": "前日",
      "lastWeek": "1週間前",
      "lastMonth": "1カ月前",
      "historyHeading": "過去90日間",
      "extremeFear": "極度の恐怖",
      "fear": "恐怖",
      "neutral": "中立",
      "greed": "強欲",
      "extremeGreed": "極度の強欲",
      "howHeading": "指数の読み方",
      "howP1": "恐怖・強欲指数は、暗号資産市場の投資家心理を0から100までの一つの数値に集約したものです。数値が低いときは投資家が恐怖に傾いている状態で、売り圧力の強まり、価格の下落、不安をあおる見出しが目立ちます。逆に数値が高いときは強欲を示し、買いが買いを呼ぶ相場、急角度で上昇するチャート、そして「自分だけが取り残されている」という焦りが広がります。",
      "howP2": "スコアは複数の指標を組み合わせて算出されます。内訳は価格の変動率（ボラティリティ）、市場のモメンタムと出来高、SNS上の話題量、暗号資産全体の時価総額に占めるビットコインの比率、そしてGoogle検索のトレンドです。公表は1日1回のため、数値は刻一刻と変わるのではなく1日単位で動きます。",
      "howP3": "この指数はもともと逆張りの発想でつくられています。「他人が強欲なときに恐怖し、他人が恐怖しているときに強欲であれ」と言われるとおり、極度の恐怖は過去に売られすぎの局面と重なることが多く、極度の強欲は調整が近づいた局面と重なってきました。あくまで市場心理を測る温度計であり、売買シグナルではありません。示すのは「今日の市場がどう感じているか」であって、「明日の価格がどう動くか」ではありません。",
      "relatedPrefix": "関連情報：韓国の個人投資家の需要が世界の価格とどれだけ乖離しているかは",
      "kimchiLinkText": "キムチプレミアム",
      "relatedMiddle": "、リアルタイムの価格は",
      "cryptoLinkText": "暗号資産マーケット",
      "relatedSuffix": "の各ページをご覧ください。",
      "tradeHeading": "暗号資産を取引する",
      "partnerOffers": "提携先のサービス",
      "sampleNote": "注：表示はサンプル値です。本番環境ではリアルタイムデータに自動で接続されます。",
      "footer": "市場データは遅延する場合があり、情報提供のみを目的としています。投資助言ではありません。"
    }
  },
  "markets-us": {
    "en": {
      "title": "US Stock Market Today",
      "description": "US stock market today: live S&P 500, Nasdaq and Dow Jones levels with top large-cap stocks, updated continuously.",
      "h1": "U.S. Markets",
      "sub": "NYSE · Nasdaq · S&P 500, Nasdaq Composite, Dow Jones",
      "benchmarks": "Benchmarks",
      "topStocks": "Top Stocks",
      "topStocksNote": "Click a company for its chart",
      "colCompany": "Company",
      "colLast": "Last",
      "colChg": "Chg",
      "colChgPct": "% Chg",
      "aboutHeading": "About This Market",
      "aboutP1": "The US session runs 9:30 a.m. to 4:00 p.m. Eastern Time, Monday through Friday, with pre-market and after-hours trading around it. The S&P 500 tracks 500 large US companies and is the benchmark most professionals quote; the Nasdaq Composite leans heavily toward technology; the Dow Jones Industrial Average follows 30 blue chips and is the oldest of the three.",
      "aboutP2": "The table below follows the mega-cap names that drive most of the index moves. Click any company for its live chart and key stats.",
      "tradeHeading": "Trade Stocks",
      "partnerOffers": "Partner offers",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "미국 증시 실시간 | 나스닥·S&P 500·다우존스",
      "description": "미국 증시 실시간 시세입니다. S&P 500, 나스닥 종합지수, 다우존스 지수와 시가총액 상위 대형주의 현재가와 등락률을 정규장(한국 시간 밤 11시 30분~다음 날 오전 6시) 내내 업데이트합니다.",
      "h1": "미국 증시",
      "sub": "뉴욕증권거래소 · 나스닥 · S&P 500, 나스닥 종합지수, 다우존스",
      "benchmarks": "주요 지수",
      "topStocks": "주요 종목",
      "topStocksNote": "종목을 클릭하면 차트가 열립니다",
      "colCompany": "종목",
      "colLast": "현재가",
      "colChg": "전일 대비",
      "colChgPct": "등락률",
      "aboutHeading": "시장 개요",
      "aboutP1": "미국 정규장은 월요일부터 금요일까지 동부시간 기준 오전 9시 30분부터 오후 4시까지 열리며, 한국 시간으로는 밤 11시 30분부터 다음 날 오전 6시까지입니다(서머타임 기간에는 1시간 앞당겨집니다). 정규장 앞뒤로는 프리마켓과 애프터마켓 거래가 이어집니다. S&P 500은 미국 대형주 500개로 구성된 지수로 시장 전문가들이 가장 많이 인용하는 벤치마크이며, 나스닥 종합지수는 기술주 비중이 크게 높습니다. 다우존스 산업평균지수는 우량주 30개를 담고 있으며, 셋 중 가장 오래된 지수입니다.",
      "aboutP2": "아래 표는 지수 등락의 대부분을 좌우하는 초대형주(메가캡) 종목을 보여줍니다. 종목명을 클릭하면 실시간 차트와 주요 지표를 확인할 수 있습니다.",
      "tradeHeading": "미국 주식 거래",
      "partnerOffers": "제휴 상품",
      "footer": "시세는 지연될 수 있습니다. 본 정보는 투자 참고용이며 투자 자문이 아닙니다."
    },
    "ja": {
      "title": "米国株式市場 リアルタイム株価｜S&P500・ナスダック・ダウ平均",
      "description": "米国株の最新市況をリアルタイムでお伝えします。S&P500、ナスダック総合、ダウ平均の水準と前日比に加え、指数を動かす主要大型株の株価と変動率も随時更新しています。取引時間は日本時間23時30分から翌朝6時（夏時間は22時30分から翌朝5時）です。",
      "h1": "米国株式市場",
      "sub": "NYSE・ナスダック｜S&P500、ナスダック総合、ダウ平均",
      "benchmarks": "主要指数",
      "topStocks": "主要銘柄",
      "topStocksNote": "銘柄名をクリックするとチャートを表示します",
      "colCompany": "銘柄",
      "colLast": "現在値",
      "colChg": "前日比",
      "colChgPct": "変動率",
      "aboutHeading": "この市場について",
      "aboutP1": "米国市場の取引時間は月曜から金曜の米東部時間9時30分から16時までで、日本時間では23時30分から翌朝6時（米国が夏時間の期間は22時30分から翌朝5時）にあたります。この前後にはプレマーケット（寄り付き前）とアフターマーケット（引け後）の時間外取引があります。S&P500は米国の大型株500銘柄で構成され、市場関係者が最も多く参照する代表的な株価指数です。ナスダック総合はハイテク株の比重が高く、ダウ平均は代表的な優良株30銘柄で構成され、3指数のなかで最も歴史の長い指数です。",
      "aboutP2": "以下の表では、指数の値動きの大半を左右する超大型株を掲載しています。銘柄名をクリックすると、リアルタイムのチャートと主要指標を確認できます。",
      "tradeHeading": "米国株を取引する",
      "partnerOffers": "提携サービス",
      "footer": "市場データは遅延する場合があり、情報提供のみを目的としています。投資助言ではありません。"
    }
  },
  "markets-japan": {
    "en": {
      "title": "Japan Stock Market Today",
      "description": "Japan stock market today: live Nikkei 225 level, USD/JPY, and Japan's biggest stocks — Toyota, Sony, SoftBank and more.",
      "h1": "Japan Markets",
      "sub": "Tokyo Stock Exchange · Nikkei 225",
      "benchmarks": "Benchmarks",
      "topStocks": "Top Stocks",
      "topStocksNote": "Click a company for its chart",
      "colCompany": "Company",
      "colLast": "Last",
      "colChg": "Chg",
      "colChgPct": "% Chg",
      "aboutHeading": "About This Market",
      "aboutP1": "The Tokyo Stock Exchange trades 9:00–11:30 a.m. and 12:30–3:30 p.m. Japan Standard Time. The Nikkei 225 is the headline index — price-weighted, so high-priced stocks move it most. Because so many constituents are exporters, the index often moves opposite the yen: a weaker yen tends to lift Japanese equities.",
      "aboutP2": "The table below follows Japan's most-watched large caps. Click any company for its live chart and key stats.",
      "tradeHeading": "Trade Stocks",
      "partnerOffers": "Partner offers",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "일본 증시 닛케이225 지수·엔달러 환율 실시간",
      "description": "오늘 일본 증시 시황을 한눈에 정리합니다. 닛케이225 지수와 엔달러 환율은 물론 도요타·소니·소프트뱅크 등 일본 주요 대형주의 현재가와 전일 대비 등락률을 실시간으로 확인할 수 있습니다.",
      "h1": "일본 증시",
      "sub": "도쿄증권거래소 · 닛케이225",
      "benchmarks": "주요 지수",
      "topStocks": "주요 종목",
      "topStocksNote": "종목을 클릭하면 차트가 열립니다",
      "colCompany": "종목",
      "colLast": "현재가",
      "colChg": "전일 대비",
      "colChgPct": "등락률",
      "aboutHeading": "시장 개요",
      "aboutP1": "도쿄증권거래소 정규장은 일본 표준시 기준 오전 9시~11시 30분, 오후 12시 30분~3시 30분에 열립니다. 일본과 한국은 시차가 없어 한국 시간(KST)도 동일합니다. 대표 지수인 닛케이225는 주가 가중 방식이어서 주가가 높은 종목일수록 지수에 미치는 영향이 큽니다. 구성 종목 상당수가 수출 기업이다 보니 지수는 엔화 가치와 반대로 움직이는 경우가 많아, 엔화가 약세를 보이면 일본 증시가 오르는 경향이 있습니다.",
      "aboutP2": "아래 표는 일본에서 가장 주목받는 대형주를 모아 보여줍니다. 종목명을 클릭하면 실시간 차트와 주요 지표를 확인할 수 있습니다.",
      "tradeHeading": "주식 거래",
      "partnerOffers": "제휴 서비스",
      "footer": "시세는 지연될 수 있으며, 정보 제공을 목적으로 할 뿐 투자 권유가 아닙니다."
    },
    "ja": {
      "title": "日本株 今日の市況｜日経平均株価・東証のリアルタイム相場",
      "description": "日本株市場の今日の動きをリアルタイムでお届けします。日経平均株価の水準やドル円相場に加え、トヨタ自動車、ソニーグループ、ソフトバンクグループなど東証の主要銘柄の株価・前日比・変動率を一覧で確認できます。",
      "h1": "日本株市場",
      "sub": "東京証券取引所・日経平均株価",
      "benchmarks": "主要指標",
      "topStocks": "主要銘柄",
      "topStocksNote": "銘柄名をクリックするとチャートを表示します",
      "colCompany": "銘柄",
      "colLast": "現在値",
      "colChg": "前日比",
      "colChgPct": "変動率",
      "aboutHeading": "この市場について",
      "aboutP1": "東京証券取引所の取引時間は、前場が9時〜11時30分、後場が12時30分〜15時30分（日本時間）です。代表的な株価指数である日経平均株価は株価平均型のため、値がさ株ほど指数への影響が大きくなります。構成銘柄に輸出企業が多いことから、指数は円相場と逆方向に動きやすく、円安局面では日本株が買われやすくなります。",
      "aboutP2": "下の表では、日本で最も注目される主力大型株の値動きをまとめています。銘柄名をクリックすると、リアルタイムのチャートと主要な指標を確認できます。",
      "tradeHeading": "株式取引",
      "partnerOffers": "提携サービス",
      "footer": "市場データは遅延する場合があります。情報提供のみを目的としており、投資助言ではありません。"
    }
  },
  "markets-korea": {
    "en": {
      "title": "Korea Stock Market Today",
      "description": "Korea stock market today: live KOSPI and KOSDAQ levels, USD/KRW, and Korea's biggest stocks — Samsung Electronics, SK Hynix and more.",
      "h1": "Korea Markets",
      "sub": "Korea Exchange · KOSPI · KOSDAQ",
      "benchmarks": "Benchmarks",
      "topStocks": "Top Stocks",
      "topStocksNote": "Click a company for its chart",
      "colCompany": "Company",
      "colLast": "Last",
      "colChg": "Chg",
      "colChgPct": "% Chg",
      "aboutHeading": "About This Market",
      "aboutP1": "The Korea Exchange trades 9:00 a.m. to 3:30 p.m. Korea Standard Time. The KOSPI covers the main board's large caps, while the KOSDAQ lists smaller growth and technology companies. Semiconductors dominate: Samsung Electronics and SK Hynix alone account for a large share of the market's value, so Korean equities often track the global chip cycle.",
      "aboutP2": "The table below follows the KOSPI's heavyweights. Click any company for its live chart and key stats.",
      "tradeHeading": "Trade Stocks",
      "partnerOffers": "Partner offers",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "코스피·코스닥 지수 실시간 | 오늘의 국내 증시, 원달러 환율",
      "description": "오늘의 국내 증시를 한눈에 정리했습니다. 코스피·코스닥 지수와 원달러 환율은 물론 삼성전자, SK하이닉스 등 시가총액 상위 종목의 현재가와 전일 대비 등락률까지 실시간으로 확인할 수 있습니다.",
      "h1": "한국 증시",
      "sub": "한국거래소 · 코스피 · 코스닥",
      "benchmarks": "주요 지수",
      "topStocks": "시가총액 상위 종목",
      "topStocksNote": "종목을 클릭하면 차트가 열립니다",
      "colCompany": "종목",
      "colLast": "현재가",
      "colChg": "전일 대비",
      "colChgPct": "등락률",
      "aboutHeading": "시장 개요",
      "aboutP1": "한국거래소 정규장은 오전 9시부터 오후 3시 30분까지 열립니다. 코스피는 유가증권시장의 대형주를 아우르고, 코스닥에는 중소형 성장주와 기술주가 상장돼 있습니다. 시장의 중심은 반도체입니다. 삼성전자와 SK하이닉스 두 종목만으로도 전체 시가총액에서 큰 비중을 차지하기 때문에, 한국 증시는 글로벌 반도체 업황을 따라 움직이는 경우가 많습니다.",
      "aboutP2": "아래 표는 코스피 시가총액 상위 종목의 흐름을 보여줍니다. 종목명을 클릭하면 실시간 차트와 주요 지표를 확인할 수 있습니다.",
      "tradeHeading": "주식 거래하기",
      "partnerOffers": "제휴 서비스",
      "footer": "시세 정보는 지연될 수 있으며, 투자 참고용으로 제공될 뿐 투자 자문이 아닙니다."
    },
    "ja": {
      "title": "韓国株式市場 リアルタイム|KOSPI・KOSDAQ株価",
      "description": "韓国株式市場の最新動向をリアルタイムで確認できます。KOSPI・KOSDAQの株価指数やドル/ウォン相場に加え、サムスン電子やSKハイニックスなど韓国を代表する主力銘柄の株価・前日比を一覧で掲載しています。",
      "h1": "韓国市場",
      "sub": "韓国取引所 · KOSPI · KOSDAQ",
      "benchmarks": "主要指数",
      "topStocks": "主要銘柄",
      "topStocksNote": "銘柄名をクリックするとチャートを表示",
      "colCompany": "銘柄",
      "colLast": "現在値",
      "colChg": "前日比",
      "colChgPct": "変動率",
      "aboutHeading": "市場の概要",
      "aboutP1": "韓国取引所の取引時間は韓国時間の9時〜15時30分で、日本時間も同じです。KOSPIは主要市場に上場する大型株で構成され、KOSDAQには成長企業やテクノロジー関連の中小型株が上場しています。半導体の存在感は圧倒的で、サムスン電子とSKハイニックスの2社だけで市場全体の時価総額の大きな割合を占めるため、韓国株は世界の半導体サイクルに連動しやすい傾向があります。",
      "aboutP2": "下の表では、KOSPIの主力銘柄の値動きを掲載しています。銘柄名をクリックすると、リアルタイムチャートと主要指標をご覧いただけます。",
      "tradeHeading": "株式取引を始める",
      "partnerOffers": "提携先からのご案内",
      "footer": "市場データは遅延する場合があります。情報提供のみを目的としており、投資助言ではありません。"
    }
  },
  "markets-crypto": {
    "en": {
      "title": "Crypto Market Today",
      "description": "Crypto market today: live prices and market caps for Bitcoin, Ethereum and the top coins, total market cap, BTC dominance and the kimchi premium.",
      "h1": "Crypto Markets",
      "sub": "Top coins by market cap · 24/7",
      "overview": "Overview",
      "totalMarketCap": "Total market cap",
      "btcDominance": "Bitcoin dominance",
      "kimchiLinkText": "Kimchi premium →",
      "colRank": "#",
      "colName": "Name",
      "colPrice": "Price",
      "col24h": "24h",
      "colMktCap": "Mkt Cap",
      "aboutHeading": "About This Market",
      "aboutP1": "Crypto never closes — prices trade around the clock, every day of the year. Total market capitalization and Bitcoin dominance (Bitcoin's share of that total) are the two quickest reads on where the market stands: rising dominance usually means money is favoring Bitcoin over altcoins.",
      "aboutP2": "Prices on this page stream live on the front page and refresh continuously here. For the gap between Korean and global prices, see the kimchi premium tracker.",
      "tradeHeading": "Trade Crypto",
      "partnerOffers": "Partner offers",
      "footer": "Market data may be delayed and is provided for information only, not investment advice."
    },
    "ko": {
      "title": "실시간 코인 시세 — 비트코인 시가총액·김치프리미엄",
      "description": "비트코인과 이더리움을 비롯한 시가총액 상위 코인의 실시간 시세와 24시간 등락률, 전체 시가총액, 비트코인 점유율, 그리고 국내외 가격 차이를 보여주는 김치프리미엄까지 한 화면에서 확인하실 수 있습니다.",
      "h1": "암호화폐 시장",
      "sub": "시가총액 상위 코인 · 연중무휴 24시간 거래",
      "overview": "시장 개요",
      "totalMarketCap": "전체 시가총액 {x} (24시간)",
      "btcDominance": "비트코인 점유율 {y}",
      "kimchiLinkText": "김치프리미엄",
      "colRank": "#",
      "colName": "코인명",
      "colPrice": "현재가",
      "col24h": "24시간 등락률",
      "colMktCap": "시가총액",
      "aboutHeading": "암호화폐 시장 정보",
      "aboutP1": "암호화폐 시장에는 휴장이 없습니다. 1년 내내 24시간 거래가 이어집니다. 전체 시가총액과 비트코인 점유율(전체 시가총액에서 비트코인이 차지하는 비중)은 시장 상황을 가장 빠르게 읽어낼 수 있는 두 가지 지표입니다. 점유율이 오르면 보통 자금이 알트코인보다 비트코인으로 쏠리고 있다는 뜻으로 해석합니다.",
      "aboutP2": "이 페이지의 시세는 첫 화면에서 실시간으로 표시되며, 여기에서도 계속 갱신됩니다. 국내 시세와 해외 시세의 차이는 김치프리미엄 페이지에서 확인하실 수 있습니다.",
      "tradeHeading": "암호화폐 거래",
      "partnerOffers": "제휴 안내",
      "footer": "시세는 지연될 수 있으며 정보 제공 목적으로만 제공됩니다. 투자 권유가 아닙니다."
    },
    "ja": {
      "title": "暗号資産の価格・時価総額ランキング — ビットコイン相場をリアルタイム更新",
      "description": "暗号資産市場は24時間365日動き続けます。ビットコインやイーサリアムなど主要銘柄の価格と時価総額に加え、市場全体の時価総額、ビットコインドミナンス、韓国との価格差を示すキムチプレミアムまでリアルタイムで確認できます。",
      "h1": "暗号資産マーケット",
      "sub": "時価総額上位の銘柄 · 24時間365日",
      "overview": "概況",
      "totalMarketCap": "時価総額合計（24時間）",
      "btcDominance": "BTCドミナンス",
      "kimchiLinkText": "キムチプレミアム",
      "colRank": "#",
      "colName": "銘柄",
      "colPrice": "価格",
      "col24h": "24h変動率",
      "colMktCap": "時価総額",
      "aboutHeading": "暗号資産市場について",
      "aboutP1": "暗号資産市場に取引時間の区切りはなく、年中無休で24時間値動きが続きます。相場の位置を素早くつかむ手がかりは、市場全体の時価総額と、そのうちビットコインが占める割合を示すビットコインドミナンスの2つです。ドミナンスが上昇している局面では、資金がアルトコインよりビットコインに向かっていると読むのが一般的です。",
      "aboutP2": "同じ価格データはトップページでリアルタイムに配信されており、このページでも継続的に更新されます。韓国国内と海外の価格差については、キムチプレミアムのページをご覧ください。",
      "tradeHeading": "暗号資産取引",
      "partnerOffers": "提携サービス",
      "footer": "相場情報は遅延する場合があり、情報提供のみを目的としています。投資助言ではありません。"
    }
  }
};
